### ISSUE TITLE
Join fields together in ingest via Regex

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#109]
I would like a mechanism to be able to join say a Date 'DD-MM-YY' and a Time 'HH:MM:SS' column (via regex) into  (YYYYMMDDHHMMSS) for better values in the datetime column.

```
Something like:
$field1 = DD-MM-YY 
$field2 = HH:MM:SS
$field3 = ($field1 =~ s/^(\d\d)-(\d\d)-(\d\d)/20$3$2$1/) . ($field2 =~ s/^(\d\d):(\d\d):(\d\d)/$3$2$1/);
```

**Comment by arcturus2** [comment]
@spjspj to clarify, do you want to be able to merge columns when using the "Import from Delimited" feature or something else?

Note that you can import data via Constellation's Rest API and use the `constellation_client.py` python client. In fact, you can also use this client to send data to Constellation via a Jupyter Notebook. If you're interested I can look at putting together a how to Jupyter Notebook for you.

**Comment by spjspj** [comment]
@arcturus2 I was just thinking of some glue type logic / wizard on the ingest of a file that would let you refer to 'field1' and 'field2' and let you concatenate those two (or more) fields into one in some meaningful way.  You could do it prior by modifying the file but there may be a use case and a simple way of being able to get data into the one meaning field.

**Comment by cygnus-x-1** [comment]
Creating values cross column is not currently possible using the Delimited File Importer (although it is a good idea), however you could achieve this using a Jupyter Notebook (Tools > Start Jupyter Notebook) as @arcturus2 eluded to. You can also do this post-ingest by using either the Attribute Editor or the Scripting View to create a new attribute from multiple existing attributes.

**Comment by serpens24** [comment]
@arcturus2:
There seem to be quite a few 'import fromX format" or similar type issues. This one probably falls into that category as it overloads the import from CSV to allow source columns to be merged.

I suspect all of these need to be considered as a tradeof between adding extra importers v reusing existing. Ie if a "blah" filetype can be easily converted to a csv file format, it may be just as easy for users to convert from blah to csv external to constellation and then import from csv to constellation.

In a similar sense - its very easy to use excel, python etc to take csv files and add rules to merge columns into other columns .... this would probably allow jupyter notebooks or similar to provide powerful importing functionlaity ... and a lot more powerful than what we can do easily via a bespoke GUI. This ould especially be the case of the tickets initial request ... regex over multiple columns to form new value.

If we were to allow column merging via the GUI, we probably dont want to go much further than allowing a constellation attribute to be mapped to multiple CSV columns, (in a given order) and allowing seperators to be included. 
IE:
in the screenshot below, if you drag Source Identifier onto 'from-partA' rather than removing it from under "Source Node Attributes" you could keep it there and alow it to be then dragged onto another column ... building up an ordered list of columns to merge. Each drag could provide a text input allowing a custom seperator to be added.
![image](https://user-images.githubusercontent.com/58677108/82779720-1ac9c280-9e94-11ea-9107-7e729d9a369c.png)

I think the above would be somewhat messy.

Another option that has come to me is perhaps in the **Source** seciton of the dialog, adding the ability to add a translate python script - this script could be identified by filename and could be generated outside of Constellation. It would probably need to implement a 'soft' interface by which it could return a success status if the conversion was successful, and result in a 'temporal CSV file being created' which would then be displayed in the central display and mapped to constellation attributes.

User could then select a file for import (and format) as is currently done, and then optionally select a transaltion script to traslate these columns programatically and displaying the results in the tabular view for assignment to attributes.

If the transaltor encountered any errors it would  need to be flagged, but it may be enough to return an empty data set ... allowing constellation to display a generic "An error occured transalting XXXXX.csv usinng translator 'YYYY.py'" type message.

**Comment by serpens24** [comment]
As discussed with @arcturus2 - there is already a form of merge functionlaity avaialbe via the bottom half of the form.. I'll check what it can do.

**Comment by antares1470** [comment]
> 
> 
> As discussed with @arcturus2 - there is already a form of merge functionlaity avaialbe via the bottom half of the form.. I'll check what it can do.

@serpens24 Did you ever get around to checking this out?

**Comment by aldebaran30701** [comment]
Closing as many other programs seem to be able to help handle this.
