### ISSUE TITLE
Moving Map and Selecting on Map 

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#110]
These are the exact opposite of the main graph window 
(Map - you move around with holding left mouse button and select a box with right mouse button)
(Graph - you move around with holding right mouse button and select a box with left mouse button)
(Scatter - you select with the left button and can't move at all :( )
Also, where the heck is the developer guide?  It's mentioned in the help text to be able to ingest a maps source or similar.

**Comment by cygnus-x-1** [comment]
Hi spjspj,

The inconsistent map controls is known problem (https://github.com/constellation-app/constellation/issues/45) and is due to the underlying map library (https://github.com/tillnagel/unfolding) not providing any way to change the control scheme. I plan to look into this sometime soon.

I hadn't thought about making the scatter plot interactive in that way - that's a good suggestion.

You can programmatically specify your own map sources by extending the MapProvider class. This is explained in the developer guide, which can be found at https://github.com/constellation-app/constellation-training.

**Comment by spjspj** [comment]
Sounds like it should be an option in the main map gui to be able to specify a given mapping resource (OpenMaps for example) source as not everyone wants to build it from scratch.

**Comment by spjspj** [comment]
Duplicate of (#45)
