### ISSUE TITLE
Map Source should be specifiable without building from source

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#111]
Would like to be able to specify the map component to use say https://www.openstreetmap.org/ as an image source without having to compile or extend code.

**Comment by arcturus2** [comment]
Thank you for raising this feature request @spjspj. It makes total sense to have this available to users however a bit more thought needs to be considered about whether this is implemented in the Core Map View module or in another module (i.e from another repository).

The idea behind this constellation module suite which we refer to "Core" is supposed to be domain agnostic and is meant to act as a framework for anyone else to extend. To that end, we've made a basic 7 zoom level map tile set available in this version so that Constellation can be used even offline.

I would agree that users would want access to open street maps and we could make this feature available in the version that users download from the constellation-app.com website.

A philosophical discussion needs to be had about which repository implements it, that's all.

**Comment by cygnus-x-1** [comment]
It'd probably be possible to write a MapProvider which asks the user for a URL to connect to (and maybe some other parameters) - i'd say that's general enough to exist in the "Core" repository.

**Comment by cygnus-x-1** [comment]
I've written map providers for OpenStreetMap, ArcGIS Online, Bing Maps and others. Unfortunately it was not feasible to create a map provider which allowed a custom URL as even with the few providers I implemented, there was almost zero commonality between their URL formats and arguments, tile sizes, etc.

**Comment by arcturus2** [comment]
Hi @spjspj just letting you know a build of Constellation that includes the different map adaptors @cygnus-x-1 developed is available [here](https://github.com/constellation-app/constellation/releases/tag/v1.20200225.104006) in this pre-release.

**Comment by spjspj** [comment]
Nice work @arcturus2 (and @cygnus-x-1)  now, 3d scattergrams :)
