### ISSUE TITLE
Investigate using Ctrl+Tab to switch graphs in left-to-right order

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1137]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

At the moment, ctrl+tab in Constellation switches between the current and previously-selected graphs. By holding down the ctrl key, you get a menu of open graphs and views to switch between. This is nice but I'd like to be able to change the ctrl+tab behaviour to instead switch to the graph to the right (or left using shift+ctrl+tab), looping back to the leftmost graph upon reaching the end.

### Steps to Reproduce

1. Open 3 graphs
2. Keep pressing Ctrl+Tab

**Expected behaviour:** Opens the tab to the right

**Actual behaviour:** Opens the previously selected tab

**Reproduces how often:** 100%

### Additional Information

My guess is that this may be a Netbeans issue which if so may be difficult to do (if so, happy to close). If that isn't the case though, doing this would align Constellation's tab switching behaviour with that of other applications (e.g. web browsers)

**Comment by GammaVel** [comment]
Hello @antares1470 . I was just wondering if the sub menu of open graphs will still be available or if Control tab will just switch between them.  
Thank you

**Comment by serpens24** [comment]
I decided to first look at how this works within Netbeans.
What was discovered is that the same behaviour is seen in Netbeans, hence this may be (as mentioned above by @antares1470) be more complex to change than if it was bespoke Constellation code. 
This will raise the question, do we want to diverge from standard Netbeans style.

My thinking is I will take a look to see if theres any obvious tweaks that adjust the netbeans ctrl+tab brehaviour, and if not, will have the discussion about whether this should change or be left as is.

**Comment by serpens24** [comment]
From https://stackoverflow.com/questions/17235366/ctrl-tab-in-netbeans-not-working-as-it-should/17355773 is the following description which suggests it may not be worth the effort of changing.

---------------------------------------------------------------------------------------------------------------------------------------------
Depending on the version of your NetBeans installation, the Ctrl+Tab, Ctrl+Shift+Tab shortcuts are hardcoded to the PopupSwitcher which appears when pressing Ctrl+Tab/Ctrl+Shift+Tab a little longer or repeatedly.

The "proper" tab switch you're probably looking for is achieved when pressing Ctrl+PgUp/Ctrl+PgDown. That should switch between tabs in a circular manner.

As for the current version (7.3.1), there seems to be no way to change the key bindings (Tools|Options|Keymap) to Ctrl+Tab/Ctrl+Shift+Tab, because they are caught by that PopupSwitcher.

The only solution that comes to my mind is to either catch Ctrl+Tab, Ctrl+Shift+Tab a level before NetBeans (with something like AutoHotkey) and forward Ctrl+PgUp/Ctrl+PgDown. Or you could modify the sources and build NetBeans yourself. See NetBeans sources, module core.windows, package org.netbeans.core.windows.view.ui.popupswitcher.
---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by serpens24** [comment]
@antares1470 - as per the extract aside, are you happy to leave code unchanged - given that Ctrl+PgUp and Ctrl+PgDown do work as you would like.

It is probably true that the behaviour of Ctrl_PgUp/Ctrl+PgDown is probably not well known in constellation (perhaps the same for Ctrl+Tab etc ...... should this be documented somewhere ?

**Comment by antares1470** [comment]
> @antares1470 - as per the extract aside, are you happy to leave code unchanged - given that Ctrl+PgUp and Ctrl+PgDown do work as you would like.
> 
> It is probably true that the behaviour of Ctrl_PgUp/Ctrl+PgDown is probably not well known in constellation (perhaps the same for Ctrl+Tab etc ...... should this be documented somewhere ?

@serpens24 I won't answer the first part just yet but I just did some testing of my own and Ctrl+PgUp/Ctrl+PgDn didn't work for me. Checking my keymap settings (which I haven't really changed at all), there wasn't anything mapped to those shortcuts and Next and Previous tab didn't have any shortcuts so I wonder whether that was a shortcut you added? I did add some shortcuts for next and previous tab though and confirmed that those actions are what we were after here

**Comment by antares1470** [comment]
To answer your first question though @serpens24, based on your research I'm happy to close this. By the sounds of it, I don't think this is going to be worth the effort required to get this to happen.
