### ISSUE TITLE
Icon on Windows 10 changes when pinned to the taskbar

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#115]
If you pin the application to the task bar in windows, the Black Mountain Tower icon changes to a big orange box.

**Comment by arcturus2** [comment]
Good pick up @spjspj. I think we might be missing an icon file at the dimensions Windows 10 is expecting (wild guess).

**Comment by serpens24** [comment]
What is interesting about this issue is that the observed behaviour only occurs the first time that you pin the appilcation to the taskbar.

Ie:

- Open constellation.

- Right click its icon in toolbar.
The big orange box is shown in the context menu.

- Select **Pin to taskbar**. 
The taskbar icon is changed to the orange box.

- right click the icon in the toolbar again.
Note that the orange box is no longer shown for the application in the context menu.

- Select **Pin to taskbar**. 
The taskbar icon is changed to the proper icon.

**Comment by arcturus2** [comment]
@serpens24 I created a new account on my Windows 10 laptop and got the behaviour exactly as you described. @spjspj can you confirm what @serpens24 has seen?

**Comment by arcturus2** [comment]
@spjspj would you be able to test this with v2? (https://github.com/constellation-app/constellation/releases/tag/v2.0.0-beta)
