### ISSUE TITLE
Colour in Quality Control View

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#132]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

The blue colour using in the Quality Control View when the score is 80 is hard to read because of the black on blue. Perhaps a different shade of blue or a different colour is needed.

### Steps to Reproduce

TBD...

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** The score when set to 80 is easy to read

**Actual behaviour:** The score when set to 80 is hard to read

**Reproduces how often:** 100%

**Comment by formalhaut69** [comment]
The issue was, when the quality was between 60 and 90 the text in the quality control view would be difficult to read because the black text would clash with the dark blue background. To fix the issue, the text colour will change to white when its between 60 and 90. Does this sound like a possible solution to this issue?

**Comment by arcturus2** [comment]
Yep, happy with that @formalhaut69
