### ISSUE TITLE
Change CTRL+Z to graph edits, not view changes

### ISSUE THREAD

**Issue by constellationuser** [constellation-app/constellation#156]
If I want to undo a change I made to a graph I use CTRL+z. However the actions included in the undo function include not only edits to the graph, but also camera moves. So I may have to do 10 or 20 ctrl+z presses to undo a single change. Please can you change this behaviour to exclude camera moves from the undo function?

Thanks

**Comment by cygnus-x-1** [comment]
Camera movement is controlled by attributes on the graph - so what you are describing is actually a graph edit. In fact, almost everything you do in Constellation is a graph edit underneath - that's part of what makes it so powerful. The undo framework does try to organise itself so that you don't have to undo many of the same types of graph edits in a row by recognising that they are the same action and bundling them together. Perhaps this isn't quite working for camera movements?

**Comment by arcturus2** [comment]
I've closed this @constellationuser based on feedback mentioned above. If this is still a problem then happy to open this and continue the discussion.
