### ISSUE TITLE
Copy to new graph default name issue

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#189]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Creating a new graph, and selecting "Copy to New Graph" will create a new graph successfully, but rename the graph as the next graph number appended. This does not appear to be intuitive that it is a copy.
![image](https://user-images.githubusercontent.com/58677759/72025279-8b968680-32c7-11ea-9431-373f1eef1279.png)

### Steps to Reproduce

1. Open Constellation
2. Open new graph
3. Copy to new graph

**Expected behaviour:** 
New graph is opened and named incrementally.
analyticgraph1 is copied to new graph named analyticgraph2

**Actual behaviour:** 
New graph is opened and new graph number is appended.
analyticgraph1 is copied to new graph named analyticgraph12

**Reproduces how often:** 
100%

### Additional Information

N/A

**Comment by formalhaut69** [comment]
What we could do here is add " - copy" in the same way that windows does instead of the additional numbers. Although, it seems that the numbers are being added somewhere outside of the CopyToNewGraphPlugin file so if this enhancement was made, it could cause issues elsewhere.

**Comment by formalhaut69** [comment]
This is the code block responsible for adding the numbers to the end of the graph names. Changing it could result in issues elsewhere, any suggestions? 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/GraphObjectUtilities.java#L62-L75

**Comment by aldebaran30701** [comment]
Ah yes, that looks like trouble to fix, considering it is utilized for other graph creation methods. Perhaps that is why the previous implementation was structured this way.

**Comment by arcturus2** [comment]
@aldebaran30701 I'm probably used to this feature how it is so I will sound biased when I say I don't think there is a problem with how it currently works 😆. I've also not had any complaints from users about this naming convention so not too keen changing it unless there is feedback from users you talk to or feedback from UX folk.

That said, happy to take suggestions if you want to continue investigating this though as it can give fresh ideas.

I don't agree with the idea of having special logic to inspect the graph name and if it happens to have a number then increment it in the copied graph.

The current logic seems simple, fast and makes sure the graph names are different and not long.

There are definitely use cases to open larger graphs in sub graphs and repeat this multiple times when working on a graph so appending " - copy" will result in long graph names and reduce the number of tabs you can see in your work area. You will have names like "analyticgraph - copy - copy".

**Comment by aldebaran30701** [comment]
I can see where you are coming from @arcturus2 with respect to - copy and how it works. I was under the impression that the naming was an issue because I opened a copy of a copy within the issue post.
I am happy to have this closed, and a new ticket can be raised in the future if there is a need for change. 👍

**Comment by arcturus2** [comment]
@aldebaran30701 I've had a chat to @cygnus-x-1 about this and I've had a re-think about this. I guess that just because no one has complained it doesn't mean there isn't anything wrong.

@cygnus-x-1 suggested maybe having a - before appending the increment number should be a little bit clearer than analyticgraph1234 perhaps.

>I don't agree with the idea of having special logic to inspect the graph name and if it happens to have a number then increment it in the copied graph.

I take this back. If you want to pursue this or another idea then go for it and I'll be happy to see what you come up with. I think at the time this was implemented, it was determined too much of a hassle to keep track of the number of graphs open and append the right number and a simple incrementing counter was "sufficient".

If you do decide to append " - copy" then to solve the problem of preventing long graph names like "analyticgraph - copy - copy" can the same thinking of incrementing a number be used so it will be something like "analyticgraph - copy", "analyticgraph - copy 2", "analyticgraph - copy 3"?

**Comment by GCHQDeveloper601** [comment]
Looking at picking this ticket up, looks like the logic here gets a little tricky as it's used for both brand new graphs and the copy method and there is no way to differentiate between the copy vs a new graph. The name passed in is simply a "type" and the counter increments regardless if a number is used at all. Would removing the number be acceptable if there isn't currently a graph with the same name? 

i.e. first graph = analyticgraph
second graph = analyticgraph1
yet another new graph = analyticgraph(++i)
copy from first graph = analyticgraph - copy
copy from copy = analyticgraph - copy 1
copy form second copy = analyticgraph - copy 2

Does this sound like a sound way forward? In order to make this work it may need another method with a property if it's a copy or a way to look through the other names and see if there is already a file with the name of what is trying to be created.

**Comment by aldebaran30701** [comment]
@GCHQDeveloper601 
I'd have to agree that it does look like the best way forward. 
I personally like the idea of sticking with a windows based naming convention.
i.e. 
first graph - analyticgraph
second graph - analyticgraph1
first graph copy 1 - analyticgraph - Copy
first graph copy 2 - analyticgraph - Copy (1)
copy of first graph copy 2 - analyticgraph - Copy (1) - Copy

**Comment by GCHQDeveloper601** [comment]
On reflection, this logic might get very complicated. For instance some users put dates at the end of the filename. 
i.e. myGraph - copy 20200815.star

I'm liking the idea @aldebaran30701 had regarding the Windows approach, but we do run the risk of very long file names. I know there is a max string length of some OS's so we may need to put a catch in to trap for abnormally long filenames and get the user to try again.

**Comment by arcturus2** [comment]
@GCHQDeveloper601 the dates in the filename is a good point and I think following the windows approach that @aldebaran30701  has suggested is a good way forward. Also agreed regarding the issue with long file names and needing inform the user to come up with a shorter name when it comes to saving the graph.
