### ISSUE TITLE
Corrupted star file caused by premature exit during save

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#19]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

If you close Constellation whilst a save is in progress, it is possible to corrupt the .star file and make it unrecoverable.

This can happen if the graph is large and it takes a few seconds to save and you force Constellation to close by clicking on the X a few times.

Trying to recover the file via `zip -FF` does not work.

### Steps to Reproduce

1. File -> Save
2. Immediately close Constellation
3. Open Constellation
4. Open the saved file successfully

**Expected behaviour:** The saved star file should open successfully

**Actual behaviour:** The saved star file becomes corrupted and is unable to be opened

**Reproduces how often:** 5%

### Additional Information

This is hard to reproduce. One method would be to create a very large graph and change the auto-save from 5 minutes to 1 minute and try to reproduce it more consistently.

**Comment by serpens24** [comment]
Feels like a difficult one to fix.
One option @arcturus2 may wish to consider is whether new saves are written to a 'tmp' filename and then moved to final name if the save completes successfully.

A little like what happens when downloading files off the net, where a temp downloading file is written until the file is completely downloaded at which time it is removed/renamed to correct name.

So, I suspect that preventing corruption of an in progress file save is impossible as generally yo ucannot guarantee successful clenaup, but we can prevent it also destroying the previous file version.

So workflow woud be:

1. graph example.star is opened
2. changes made
3. save is requested by user
4. file starts to be saved to example.starburst
5. if save completes completely, a completion point is reached and file is renamed to example.star (replacing original)
6. if save fails to get to completion point, then rename is never triggered. The example.starburst file is going to be corrupted in all likelyhood..... but example.star will still exist.

**Comment by arcturus2** [comment]
Hey @serpens24 yep this is a tough one. I like your approach here.

I was interested in exploring the possibility of using a `Runtime.addShutdownHook(Thread t)` and figure out the logic in the hook, perhaps something like what you have described?

Side tracking a bit but somethings to keep in mind is that we are using the built in NetBeans Auto Save feature as well which saves files to `.CONSTELLATION\Autosave`. If Constellation is terminated prematurely and there are auto save star files, you get prompted to restore them when you open Constellation again.

Getting back on track with what this issue is about, it's when someone clicks save (on a large graph) and then immediately clicks on the close button to shutdown Constellation (because they are in a hurry to go home)...which prematurely terminates the save.

**Comment by aldebaran30701** [comment]
From what I understand, the file save currently implements as @serpens24 mentions. See below for current implementation.
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/visual/VisualGraphTopComponent.java#L921-L956

Feel free to correct me, but I fail to see it corrupting a file due to this section. 
Is the issue the corruption of the file, or the premature termination of the save (loss of new data since auto-save)?

**Comment by arcturus2** [comment]
I've had a user let me know yesterday they had this problem just yesterday. The .star file looks corrupted because it's not a valid zip format when I looked at it. I think it is a premature termination of Constellation that causes the file to be corrupted @aldebaran30701.

**Comment by serpens24** [comment]
OK - so I've added a proof of concept commit which demonstrates a redundancy mechanism, by which loading of a file will look for a backup if the selected file throws an exception upon load.

The basic approach is:

On save of an existing file
-----------------------------
a). make a copy of the existing saved file   (BACKUP_FILE)
b).  launch the processing to save the new file contet over top of the original file    (ORIGINAL_FILE)

In theory this means that:
* if a) fail, then the ORIGINAL_FILE is untouched so should be valid (or at least shouldnt have been corrupted by constellation)
* if b) fails, the BACKUP_FILE should already have been created, so should still be valid.

This is not foolproof as disk corruption or ewxternal factors could result in corrupted files, but theres little that can be done about those cases, this change is aimed at addressing corruption caused by Constellation.

 
On load of a file
------------------
a) attempt to load ORIGINAL_FILE and if successful use that file  (question - should backup then be removed ?)
b) if a) fails look for a backup file and load it if found.  If b) fails, then somehow both the original and backup have been corrupted



NOTE: This first commit is focussing on the normal save operation, next stage will be to consider autosave.

@arcturus2  to experiment with this issue, branch https://github.com/constellation-app/constellation/tree/Issue%2319-CorrupStarFileHandling can be pulled. 

I found the easiest way to generate a corrupt file is to create a very large sphere graph (100k - 200k nodes) then during save use task manager to kill the process .... this should result in an incomplete file. 

So process is, creatre large graph - save is correctly to ensure you have a 'good file'. Then save it again - to get a backup file (<filename>_bak in same folder).  Finally, save it again, but this time kill constellation during the save. (confirm file sizes are different)

You should then be able to show that rying to laod the file will show a message in the bottom bar indicating backup file is being used and that it loads.

Restart cnstellation, rename the backup file and try to load again and confirm an error is reported and the graph doesnt load .. showing that a lack of backup file means the file wont load.

**Comment by serpens24** [comment]
Some Cases to test for, and expected results:

|  File  |  Backup  |  AutoSave | Notes |
|-------|----------|-------------|--------|

**Comment by GammaVel** [comment]
Reviewed this issue. As noted in the comments with the test scenario there is an issue where there is a valid .BAK and invalid .STAR file and Auto file. The bak file ends up being corrupted and can't be opened. Can this be fixed? Happy to create a new issue for this. 

Also, there is a minor issue with the logging in some scenarios which has a Warning that the backup file is being opened when it has not,  This applies for the following scenarios:




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///D:/Users/Kelly.Zyla/AppData/Local/Temp/31/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///D:/Users/Kelly.Zyla/AppData/Local/Temp/31/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





F | B | A | F
-- | -- | -- | --
F | B | A | A
F | B | A | F
F | B | A | F
