### ISSUE TITLE
Export to SVG causes the graph to lock indefinitely when interrupted

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#1951]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When exporting a graph to an SVG file there is the potential for a graph to be locked indefinitely. If a user exports a graph, and cancels the export prematurely, the graph is not released by the plugin due to the way the plugin utilizes `GraphVisualAccess`. This locks the graph. This may be an indication that `GraphVisualAccess` is not the appropriate utility to use to get visual information from the graph.

Using `VisualGraphUtilities` would be a more appropriate utility class to use however would require significant work to support the needs to the SVG export plugin.

### Steps to Reproduce

1.  Greate a sphere graph with 10000 Nodes

2.  Export the graph to SVG

3.  Cancel the Export

4. Note the graph has not locked indefinitely.  

**Expected behaviour:** 
The graph should be released appropriately when the plugin is canceled. 

**Actual behaviour:**
The graph locks.

**Reproduces how often:**
When canceled during execution.

### Additional Information

N/A

**Comment by HolandCrick** [comment]
@capricornunicorn123 thanks for your efforts to "The Graph Lock indefinitely during SVG Export Cancellation from progress"

It works when graph size is within 12K nodes and 5k Transactions. Unfortunately, when graph size increase to 15k/5k or above the Graph Lock **intermittently** for indefinitely during SVG Export Cancellation. Also noticed that the time taken for large graph 10k/5k to 15k/5k or above is too long. SVG export for 5k/5k sphere graph took just over 6 mins, 10k/5k graph took 16.5 mins and 15k/5k took 24min. Performance wise it not a great result. Probably would be worth investigating whether we can improve the performance.
Consider alternate SVG formats, which may improve memory efficiency. From a UX perspective it's worth to add a limit the size of the graph that can be exported so that the plugin throws an error if the graph is too big.

**Comment by HolandCrick** [comment]
@capricornunicorn123 Thanks to resolving the SVG file export issue. The Worning over >5000 elements is a good idea.  The added warning label to the parameter window and some stylistic enhancements look great.


![image](https://github.com/constellation-app/constellation/assets/157770877/5b59f618-6935-48dc-ba03-4b0b092f4ccd)
