### ISSUE TITLE
Analytic View Colour, Size and Hide Toggles stay active when closed

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#201]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Adding or editing the options in the run menu of the Analytic View will stay active when the menu is closed. This makes the user run the plugin again to clear the state left by the toggled options.
Is this intended behaviour? Would there be a use case for needing the colours to remain active? If so, the possibility of a clear set state button to revert without re-running a plugin or undo -ing actions.

### Steps to Reproduce

1. Create default graph using sphere builder
2. Save file (possibly not necessary)
3. Launch Analytic View
4. Select questions menu -> "Has closest relationship" -> RUN
5. Toggle any number of values such as colour, size and hide slider
6. Close Analytic View

**Expected behaviour:** 
Selected toggled values are cleared - when you close the graph any changes made using the Color Hide or Resize, should be removed. 

**Actual behaviour:** 
Graph state remains as toggled (greyed colours, large transactions, hidden transactions)

**Reproduces how often:** 
100%

### Additional Information
There is no need to have a reset button here

**Comment by arcturus2** [comment]
@aldebaran30701 just a quick shout out to say thanks for being proactive and creating these issues to make sure things are consistent and putting fresh eyes and energy back into the app!

@cygnus-x-1 is this how you designed the Analytic view to work or is it a bug?

I ask because @aldebaran30701 and @serpens24 have fixed bugs with K-Truss and Hierarchical Clustering views to revert the graph to how it was when interactive mode is turned off or the view is closed. The analytic view seems to behave differently.

**Comment by cygnus-x-1** [comment]
The Analytic View was designed to maintain its state (the _AnalyticViewState_ meta-attribute) even when the view is closed (as were the clustering views originally, which is why they have that _interactive_ button). This is currently not that useful as the Analytic View doesn't update its GUI using that state when you switch graphs or close and open the view (I think it currently just resets itself - there is a ticket for this issue). I don't mind the idea of having visual changes on the graph reset when you close the view, so long as they are then reapplied when you open the view again.

**Comment by GammaVel** [comment]
Updated the expected results here -when you close the graph any changes made using the Color Hide or Resize, should be removed. There is no need to have a Reset button. When you return to the Analytic view there is no need to remember the last state as it is most likely that other changes will have been made to the graph.

**Comment by OrionsGuardian** [comment]
Randomly clicking between the colour, size, and hide options gave this exception:

![image](https://user-images.githubusercontent.com/104604488/232356258-7b349351-717d-44f5-aac1-d5a14b12123d.png)

**Comment by GammaVel** [comment]
Observed a random run time error when in the analytic view and randomly clicking on the graph:
![image](https://github.com/constellation-app/constellation/assets/83679004/03c6eacb-611f-4163-ad7c-209fb1c08d8e)

**Comment by GammaVel** [comment]
Thank you @Delphinus8821 for getting this one working, so good to see especially seeing it is an older issue. Looks really good. I did notice the same thing that you listed as a drawback in your MR - if the graph is saved the changes are retained which kind of makes sense.
