### ISSUE TITLE
Table View column layout as a preferences

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#226]
> As an analyst
> I want to be able to save my column preferences 
> so that I can save time from doing this manually for each graph I analyse

The table view allows you to select the columns you want to see and order them to your preference. It would be great to have this layout saved as a preference.

This would ideally require a new option in the table view to manage (add/remove) layouts you define.

**Comment by formalhaut69** [comment]
![image](https://user-images.githubusercontent.com/58677762/74200673-7b533c00-4cb7-11ea-85db-29db7df27911.png)
So I've added the settings icon in but I think it looks a little bit squashed, perhaps because of the resolution difference. Its 192x192 instead of the 256x256 that the rest of the icons have. @arcturus2 do you think this is an issue?

**Comment by arcturus2** [comment]
Hi @formalhaut69 it would be better if all of our icons were 256x256 please. I think it looks ok and there isn't much we can do about it because the right arrow takes up some of the space. If you can however make the icon 256x256 so it's consistent with the other icons that would be greatly appreciated.

**Comment by serpens24** [comment]
I sued the heart icon for the commit I have made. Happy to change to a settings icon down the track of you prefer .. I hadn't read the comments here when I got involved. I was focuseed on getting the mechanics of the save/restore working.
