### ISSUE TITLE
Type properties missing after pasting nodes to a new graph - Copy Paste bug

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#326]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If you copy an unsupported type which has properties, Ctrl+U copies it OK but a Ctrl+C to Ctrl+V does not work

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Type properties are copied to a new graph

**Actual behaviour:** Type properties are not copied to a new graph

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by cygnus-x-1** [comment]
This is a known bug and so there should be a duplicate ticket (assuming we copied it across). We actually came up with a solution to this (documented in the duplicate ticket presumably), but didn't have time to implement it.

**Comment by sol695510** [comment]
> This is a known bug and so there should be a duplicate ticket (assuming we copied it across). We actually came up with a solution to this (documented in the duplicate ticket presumably), but didn't have time to implement it.

@cygnus-x-1 do you have the solution to this issue? Did you want to implement it or if you don't have one can I work on this issue?

**Comment by arcturus2** [comment]
@cygnus-x-1 I didn't get a chance to create a ticket for this originally on GitHub so this ticket is the issue. Sadly a solution hasn't been documented though.

@sol695510 you are free to take this one - it will be a good one to have fixed. To you need any more information before starting this?

**Comment by sol695510** [comment]
> @cygnus-x-1 I didn't get a chance to create a ticket for this originally on GitHub so this ticket is the issue. Sadly a solution hasn't been documented though.
> 
> @sol695510 you are free to take this one - it will be a good one to have fixed. To you need any more information before starting this?

@arcturus2 @cygnus-x-1 what are you referring when its stated an "unsupported type"? Is it referring to attributes?

**Comment by arcturus2** [comment]
@sol695510 I've had trouble reproducing this though it is a known issue. An `Unsupported` type is a type that the schema knows about but isn't a first level schema type with an icon, colour etc.

This isn't reproducible in the analytic schema but hypothetically say we wanted to model the human DNA, we might want to register each molecule in a "DNA schema" as its own type so they are defined as separate nodes but not other about adding them with different icons to the schema; you can introduce an `Unsupported` type and load all of the molecule types as `Unsupported`.

Every `Type` in Constellation, be it a registered first class Type, "Unsupported" and even the `Unknown` type have a properties map.

When you copy a node from one Analytic graph into another, the schema is able to detect the type and set it to the node.

With the Unsupported type for some reason this isn't happening. @cygnus-x-1 would you be OK for me to move the `Unsupported` type definition into Constellation Core so that anyone extending a Schema can benefit from the `Unsupported` type?

**Comment by cygnus-x-1** [comment]
> With the Unsupported type for some reason this isn't happening. @cygnus-x-1 would you be OK for me to move the `Unsupported` type definition into Constellation Core so that anyone extending a Schema can benefit from the `Unsupported` type?

That sounds fine to me.

**Comment by arcturus2** [comment]
I think the issue has something to do with `CopyToClipboardPlugin`.
