### ISSUE TITLE
Cannot Export Tables to Excel

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#329]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In Table View, I try to export a table of data to Excel. It looks like it all works, I save on my Desktop but then nothing actually happens (the document doesn't appear). I asked a teammate to do the same thing, he went through the same process as I did, and it worked, so not sure what the issue is?

This seems to be an intermittent issue and the exception is:
 
```java
java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(Unknown Source)
	at org.apache.poi.util.TempFile$DefaultTempFileCreationStrategy.createTempFile(TempFile.java:105)
	at org.apache.poi.util.TempFile.createTempFile(TempFile.java:60)
	at org.apache.poi.xssf.streaming.SheetDataWriter.createTempFile(SheetDataWriter.java:80)
	at org.apache.poi.xssf.streaming.SheetDataWriter.<init>(SheetDataWriter.java:63)
	at org.apache.poi.xssf.streaming.SheetDataWriter.<init>(SheetDataWriter.java:68)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheetDataWriter(SXSSFWorkbook.java:292)
	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:69)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:624)
Caused: java.lang.RuntimeException
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:628)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:645)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewUtilities$ExportToExcelFilePlugin.execute(TableViewUtilities.java:191)
	at au.gov.asd.tac.constellation.pluginframework.templates.SimplePlugin.run(SimplePlugin.java:65)
[catch] at au.gov.asd.tac.constellation.graph.node.pluginframework.DefaultPluginEnvironment$1.call(DefaultPluginEnvironment.java:125)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Tables get exported to an Excel File

**Actual behaviour:** Tables are not being exported to an Excel File

**Reproduces how often:** Sometimes

### Additional Information

N/A

**Comment by formalhaut69** [comment]
This issue must occur very rarely, I spent about a half hour trying to replicate it and couldn't get it to replicate once.

**Comment by serpens24** [comment]
I haven't yet been able to replicate, but I do not that the code under the covers uses parent.getCurrentGraph().getId() to allocate a sheet name for a sheet within the resulting spreadsheet.
Does this ID have meaning to the end user... ie 'a84951a8-2b4d-436a-b561-435b3d6' is not overly user friendly. I can understand the GUID is going to be unique. Alternates vcould be graph name or leaving the value blank, probably meaning sheet1 as the default name.

**Comment by serpens24** [comment]
I searched google for the lower level exception and found the following: https://stackoverflow.com/questions/29285076/java-apache-poi-sxssfworkbook-unable-to-create-sheets

https://bz.apache.org/bugzilla/show_bug.cgi?id=57200

This appears to be the same issue ... I will dig into these wider issues and look for a solution.

**Comment by serpens24** [comment]
OK. I have been able to replicate this problem, both on the older version of Constellation, as well as 2.0.0 Beta.

The following steps will trigger it .. although it appears there is some level of luck about it failing which I suspect is a race condition. At the heart of the problem is how the XSSFW packages generate the Excel file, in that they make use of the temporary directory - as specified by the variable: **java.io.tmpdir** (which on a Windows 10 machine seems to resolve to the **TEMP** or **TMP** environment variables, which on my machine at least are set to **%USERPROFILE%\AppData\Local\Temp**.

Within this folder, a directory **poifiles** is created by the POI library (refer to first reference in my earlier comment). This directory seems to be automatically created if it does NOT exist, however the race condition 'seems' to be that if it does not exist, often the Excel file is not created (on the desktop) or wherever the user requests it.

The references talk about the fact the poifiles directory is shared by applications, so if one were to close and delete the directory while the other wasopen, the issue could occur, however my approach to triggering it was more brutal. I open Constellation export data to excel from tableview and then manually delete the directory: 
*%USERPROFILE%\AppData\Local\Temp\poifiles**

If I then try to export tableview to excel again (having NOT restarted Constellation) I find that often the new file isn't created. This often happens the first couple of times, and I had more luck exporting nodes rather than transactions .. although this may not be the case.
In the above case I fopund that the failed attempts still created the poifiles directory, so perhaps the race condition is that this directory takes to long to be created and perhaps the code is trying to use the temp folder bnefore it exists.

The referenced links make some suggestion that there may be ways to create exclusive temp directories per POI application, but an alternate solution may be to ensure the directory exists just prior to the attempt to save...

**Comment by serpens24** [comment]
Basic steps to reproduce:
1) Open a windows Explorer window to **%TEMP%** and another to Desktop
2) Start Constellation, Create a new empty graph and open the Table View
3) In Table view,select to view Nodes
4) In Tableview, select Export to Excel, select Desktop, then enter the name **test1**
5) Confirm that a directory **poifiles** has been created inside **%TEMP%** if it didn't already exist
6)  From Windows Explorer delete the directory **poifiles**
7) In constellation, in TableView elect Export to Excel, select Desktop, then enter the name **test2**
NOTE: At this point, often I find the file **test2** is not created on the desktop - if it's not created there, is seems to be created 'elsewhere'. 
My suspicion is there is some form of race condition such that when the POI library checks for the **poifiles** directory and creates it if it does not exist, if this directory isn't created fast enough the failure occurs.

**Comment by serpens24** [comment]
I found that adding the following code as the first lines of code inside the try block within the execute function ensures that the poifiles directory exists prior to it being rerquired and appears to end the race condition. Perhaps this change is enough to close out the ticket.

`
                File poi_dir = new File(System.getProperty("java.io.tmpdir"), "poifiles");
                if (!poi_dir.exists())
                {
                    poi_dir.mkdir();
                }
`
