### ISSUE TITLE
Make global parameters singletons

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#331]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently, global parameters are being rebuilt inside each plugin which has resulted in discrepancies where the global parameter is not configured the same way within a plugin. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** global parameters built outside of plugin

**Actual behaviour:** global parameters built inside each plugin
**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sol695510** [comment]
@antares1470 did you have any suggestions as to where the global parameters should be built?

**Comment by arcturus2** [comment]
Just jumping in here too. For some more background had a look at the following and see how `DateTimeRangeParameterType` is being built again.

https://github.com/constellation-app/constellation-training/blob/32d97260c4e7b1bfeebe3ed30435fd215ce8b2a5/constellation-training-solutions/TrainingSolutions/src/au/gov/asd/tac/constellation/training/solutions/chapter4/ChainCitiesPlugin.java#L60

To be able to use the date range the user wants to query on the `DateTimeRangeParameterType` needs to be available to the plugin. you can see how its being used 

https://github.com/constellation-app/constellation-training/blob/32d97260c4e7b1bfeebe3ed30435fd215ce8b2a5/constellation-training-solutions/TrainingSolutions/src/au/gov/asd/tac/constellation/training/solutions/chapter4/ChainCitiesPlugin.java#L68

So back on line 60 what we should do rather than newing instances is get the existing instance of `DateTimeRangeParameterType` - i.e these should be singletons.

I was thinking of using a builder pattern so when say build - it will either built it or give you an instance of it if the builder has previously built it.

Happy for other suggestions to. Note that global parameters are used in other modules (like the Training module suite) so minimal breaking API changes is highly desirable.

**Comment by antares1470** [comment]
> @antares1470 did you have any suggestions as to where the global parameters should be built?

@sol695510 this actually wasn't one of my suggestions so I don't really have much else to add. I just happened to be the one who created the ticket :)

I think @arcturus2 gave a pretty good explanation though of what I think we're after here. I certainly couldn't add anything extra to that

**Comment by sol695510** [comment]
@arcturus2 thanks for the background information. Do you know generally how to find where global parameters are? I'm going off the assumption that they are just the variables being used that are public static, but that seems like there's a lot if we're just looking for ones that are being "newed" instead of calling the static instance. Just some more clarification, apologies if this is obvious.

**Comment by arcturus2** [comment]
@sol695510 don't worry about it, just ask whatever you need to until it becomes clear - its a big code base.

So this ticket is specifically looking at plugins that use parameters of the interface `GlobalParameters`. The implementation of this interface in Core is `CoreGlobalParameters` instances of these are the "query name" and "datetime range". If you do a "Find Usage" on `CoreGlobalParameters` the only plugin I see is `TestParametersPlugin`. Specifically see these lines:

https://github.com/constellation-app/constellation/blob/9758216cbbb004a5ee834b28086004c5fee62062/CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPlugin.java#L181-L185

Depending on whether plugins need to change too, please make sure to update the code in constellation-app/constellation-training.

Let me now if you need anything else.

**Comment by sol695510** [comment]
![Singleton Types](https://user-images.githubusercontent.com/58677774/83106217-3c78b300-a0fb-11ea-8576-9e12f15e0198.PNG)
Parameter Types as shown in PluginParameterType.java

**Comment by sol695510** [comment]
![Singleton Building](https://user-images.githubusercontent.com/58677774/83118789-fc6efb80-a10d-11ea-9ac7-5afc75feefdb.PNG)
**Fig 1.** CoreGlobalParameters.java

![Singleton Getting](https://user-images.githubusercontent.com/58677774/83118828-07c22700-a10e-11ea-8833-b57eb1533caf.PNG)
**Fig2.** TestParametersPlugin.java

I have been looking over the CoreGlobalParameters implementation and how the PluginParameters are structured for a way to implement the singleton pattern. Just to clarify that I have the correct way of thinking for implementation I’ll go over it below.

CoreGlobalParameters would hold a Map<String, PluginParameter> This will hold the instances of the plugins identified by the ID. A check to see if an entry is in the map and not null would determine if an instance was created (using.build()) or an existing one was returned, see Fig 1.

The idea was to be able to pass an ID into CoreGlobalParameters.getPluginParameter(String ID) and it would return a generic PluginParameter<?> which ? could be of type StringParameterValue.
This above solution would be scalable and also manage to store any amount of parameters of any type within the list.

The issues realized when implementation came around was to do with creating an instance when one did not exist. We need to be able to create the type needed. So the getPluginParameter(String ID) method would effectively build a PluginParameter<?> of any type ?.

The issue with this is that the .build() method is a static and the parent method of PluginParameter<StringParameterValue> (or any other ParameterValue for that matter). The static method cannot be inherited from the parent method so we could not build the child item from generic access.

Another possibility was making a generic method within the parent of the PluginParameter<StringParameterValue> and then calling each subtype’s static method from the parent context. I could not get this to work either. 

I’m lost on direction for how to proceed with this issue without possibly refactoring (which may also not work).

**Comment by sol695510** [comment]
@arcturus2 @cygnus-x-1, forgot to tag you in the above comment.

**Comment by cygnus-x-1** [comment]
From memory, the crux of the issue was that the current global parameters implementation relies on each plugin developer re-building those parameters using a common parameter id. What we really want is for global parameters to already have been built and for all plugins to have access to them. 

I'd imagine this being analogous to how any plugin can access a pre-built version of any `SchemaVertexType` via its `SchemaConcept` class. So you might have some generic functions in the `GlobalParameters` class for things like "lookup by string" if it makes sense, but the standard way of accessing these parameters would be something like:
```
parameters.addParameter(CoreGlobalParameters.QUERY_NAME_PARAMETER)
parameters.addParameter(CoreGlobalParameters.DATETIME_RANGE_PARAMETER)
```

**Comment by sol695510** [comment]
> From memory, the crux of the issue was that the current global parameters implementation relies on each plugin developer re-building those parameters using a common parameter id. What we really want is for global parameters to already have been built and for all plugins to have access to them.
> 
> I'd imagine this being analogous to how any plugin can access a pre-built version of any `SchemaVertexType` via its `SchemaConcept` class. So you might have some generic functions in the `GlobalParameters` class for things like "lookup by string" if it makes sense, but the standard way of accessing these parameters would be something like:
> 
> ```
> parameters.addParameter(CoreGlobalParameters.QUERY_NAME_PARAMETER)
> parameters.addParameter(CoreGlobalParameters.DATETIME_RANGE_PARAMETER)
> ```

I think the implementation here #559 is similar to what you've described. Advise if otherwise.
