### ISSUE TITLE
Import from delimited date-time CUSTOM input issues

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#34]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

If you import from Delimited file, and select "custom" for your time stamp to input the correct format, I it doesn't always allow you to input stuff into the user-input field. This occurs specifically if you have already tried to apply a Date-time template to your column.

A work around that seems to work is to close and open the custom date dialog and it works the 2nd time. This has been tricky to debug.

### Steps to Reproduce

1. Open Delimited Importer
2. Right Click on the `DateTime` attribute
3. Select Formatter -> Datetime
4. Select Custom
5. Enter a custom date format

**Expected behaviour:** User can enter a custom date format

**Actual behaviour:** The field is disabled, preventing anything being typed in

**Reproduces how often:** 50%

**Comment by formalhaut69** [comment]
Spent some time on this issue but I can't seem to get to the root of the bug. The issue seems to occur 100% of the time for me whenever any date format other than CUSTOM is selected and then the Datetime Parameters window is reopened. The CUSTOM textbox overall seems to be behaving very strangely. I've observed it's setEnabled() method to have two different effects; changing line 82 to disable the CUSTOM textbox or removing the line entirely will have the same effect of the bug itself (the textbox appears to be enabled but nothing can be typed in). Whilst on line 89, the setEnabled() method functions as expected before the bug occurs so the textbox, along with the small drop down list next to it are disabled and greyed out. 
https://github.com/constellation-app/constellation/blob/36f1c51aa421095e9771f0d539aa0a6741d84b19/CoreImportExport/src/au/gov/asd/tac/constellation/importexport/delimited/translator/DatetimeAttributeTranslator.java#L77-L91

**Comment by serpens24** [comment]
I have experimented with a couple minor changes to allow this to work. ssentially there are 2 settings on the widget that are in play (found in thew code for ValueInputPane) these are its editable state and its disabled state.

The existing code constructor in ValueInputPane.java has the following blocks of code of interest:

Lines 187-194
`
            // Making the field enabled but not editable gives no visual indication of the fact that it isn't editable.
            // Making the field disabled makes it hard to read and disables the scrollbar.
            // Take the lesser of two evils.
            field.setEditable(parameter.isEnabled());
            field.setManaged(parameter.isVisible());
            field.setVisible(parameter.isVisible());
            this.setManaged(parameter.isVisible());
            this.setVisible(parameter.isVisible());`

Lines 260 - 263 (in parameter.addListener)
`
                        case ENABLED:
                            field.setDisable(!pluginParameter.isEnabled());
                            recentValuesCombo.setDisable(!pluginParameter.isEnabled());
                            break;
` 

Noe the first block above says that upon creation the **Editable** state of **field** is set but NOT its **Disable** state, but that when the parameters **Enabled state** changes that the **field** (and **recentValuesCombo**) **Disable** state only but not its **Enable** state. This mismatch seems to be causing the problem, so I experimented as follows:

Modifed block A above to add the following:
field.setDisable(!parameter.isEnabled());
recentValuesCombo.setDisable(!parameter.isEnabled());

That way, if **field** is set to **Editable** (because the parameter is enabled) then we need to un-disable it and the **recentValuesCombo** component..... ie if its ennabled you shoudl be able to change values. vice versa, if the parameter is disabled, then not only should **field** and **recentValuesCombo** be set to not **Editable** but also the widgets should be disabled.

Similarly, in the liastener case statement (which is picking up changes) if ENABLED is changed then not only should the disabled state be changed (as it does now) but also the enabled state.

when the above is all done , one thing is left to do - the code below found at lines 80-84 of DateTimeAttributeTranslator.java currently hard code the initial **Enabled** state of the customParam element to True, but this isn't correct - is should only be enabled if a "CUSTOM" format is being used.

`
        // The custom field wont enable inside the addMasterController until you
        // click on OK and open it again. This is a work around until it can be fixed.
        customParam.setEnabled(true);
        customParam.setStringValue("");
        parameters.addParameter(customParam);`


Making all of the ablove changes made the picker behave as I expected, however I do have a concern about the comments in the legacy code, in particular the following two comment blocks:

1. From ValueInputPanel.java:187 - my question is, are there examplers of where this code is used elsewhere that I dont know about that demonstrate the problem being mentioned ....
`
            // Making the field enabled but not editable gives no visual indication of the fact that it isn't editable.
            // Making the field disabled makes it hard to read and disables the scrollbar.
            // Take the lesser of two evils.

2. From  DateTimeAttributeTranslator.java:80 - is this workaround still valid, I couldnt see any issues with when the customPanel is enabled or not after my changes.
`
        // The custom field wont enable inside the addMasterController until you
        // click on OK and open it again. This is a work around until it can be fixed.
        customParam.setEnabled(true);
        customParam.setStringValue("");
        parameters.addParameter(customParam);`

@arcturus2, I tried doing a git blame but it looks like all of the code in question has been there since it was added to github so I'm unsure who to talk two about these two concerns.

**Comment by serpens24** [comment]
Note, in testing this issue I found some additional exceptions that can raise with invalid date formats being entered, these are captured in the linked issue, however the change is pretty simple - basically just modify the transalte method at line 97 of DateTimeAttributeTranslator.java to also catch these other exception types. I'll submit that fix as seperate pull request associated with #217

**Comment by serpens24** [comment]
Testing:
1. Open new graph.
2. Select Import->From Delimited File ....
3. Select file to import containing a timestamp and drag DateTime from Transaction Attributes column onto it.
4. Right click on Datetime and select Formatter->Datetime.
_Confirm that the Custom Format text entry field is disabled and unable to be selected for edit_
5. Modify the Datetime Format value to CUSTOM.
_Confirm that the Custom Format text entry field is enabled and able to be selected for edit_
6. Change the Datetime Format value a few times including some changes to and from CUSTOM as a value.
_Confirm that the Custom Format text entry field is enabled and able to be selected for edit ONLY when CUSTOM is set as a format_
7. Modify the Datetime Format value to CUSTOM.
8. Enter a valid custom format in line with the raw data and press the OK button.
_Confirm the values are shown with correct formatting_
9. Right click on Datetime and select Formatter->Datetime.
_Confirm the previously set CUSTOM format is displayed and is editable._
10. Repeat step 6 and confirm behaviour is still correct.
**Now testing exception handlling as discussed in #217 **
11. Select CUSTOM format and enter yyyyyyyyyyyyyyyyyyyy.
_Confirm no exception is thrown but datetime values all show with text = ERROR_
12. Right click on Datetime and select Formatter->Datetime.
_Confirm the previously set CUSTOM format is displayed and is editable._
13. Select CUSTOM format and enter aa.
_Confirm no exception is thrown but datetime values all show with text = ERROR_
