### ISSUE TITLE
Improve the Hierarchical Arrangement Plugin

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#372]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The current hierarchical arrangement plugin requires a seed set to be defined by the user, and often results in a less than desirable layout.

This arrangement should be redesigned to;
- Infer what the selection should be (most neighbours, centrality score)
- Layout the dependants so they look good and work with a large number of nodes at each level

**Comment by OrionsGuardian** [comment]
The redesign should simply layout the elements in a strict top-down hierarchy.
It currently has offshoot element groups which go above the origin point, messing up the visual aspect of the main hierarchy.

Also, it would not be practical to run an analytic to determine the top node(s) of the hierarchy.
It is a simple enough process to select the desired nodes and assign them to a named selection.
Then de-select all nodes and run the Hierarchical Arrangement (Ctrl-H) and choose your named selection.

Could consider an alternative approach to running arrangements that currently require named selections ...
We could pop up an option to use any currently selected nodes as the key nodes for the arrangement which will be run on the entire graph ...
Otherwise, select a Named Selection and run the arrangement on the currently selected elements only (or the whole graph if no elements are selected).

It would feel much more intuitive to select an element and run a hierarchical arrangement, expecting that selected element to be the top of the hierarchy.

**Comment by HolandCrick** [comment]
@OrionsGuardian  - Thanks for working on Hierarchical  enhancement. I found few issues while testing Hierarchical Arrangement:
 a) Graph Frozen when applying Hierarchical Arrangement in any large graph <50k nodes; small graph is working fine.
 b) Get Exception when closing Large Frozen Graph
 c) Hot Key Ctrl+H  for Hierarchical Arrangement is not working.
Please do bit more around the large graphs.

**Comment by HolandCrick** [comment]
Re-Tested 24/10/2024:
I am still having issue in Hierarchical Arrangement Functionality. Can you please look into these issues:
a) Shortest Path button - missing tool-tip; Help button need some additional explanation in help page for the Shortest Path button.
b) Large Graph still hang when apply Hierarchical Toggle Enabled.
c) Clusters left / right arrows or Cluster Graph - one of them should change. Either the hierarchy should be flipped somehow, or the buttons should be changed to up/down (and moved next to each other).

**Comment by HolandCrick** [comment]
@OrionsGuardian Thank you for improving the Hierarchical Arrangement Functionality. The enhancement working well.
