### ISSUE TITLE
Resolve NB11 JDK11 Graph Offset Issue

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#387]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The migration to NB11 is nearly complete, with just one issue which effects JDK11.
#11 - Awaiting response from JOGL Developers to develop a fix in the next release.

Issue 1374 is the issue relating to the graph offset issue.
https://jogamp.org/bugzilla//show_bug.cgi?id=1374#c3

Tracking for next release cycle of JOGL. 
https://jogamp.org/wiki/index.php?title=SW_Tracking_Report_Feature_Objectives_Overview#High_DPI

Closing #219 to make this the new master ticket for the remainder of NB11/JDK11 migration.
### Steps to Reproduce

See Ticket #11 

**Expected behaviour:** 

**Actual behaviour:** 

**Reproduces how often:**

### Additional Information
N/A

**Comment by arcturus2** [comment]
I've had a go to build JOGL and add the patch mentioned in http://forum.jogamp.org/canvas-not-filling-frame-td4040092.html#a4040210 but didn't have any luck seeing a change. Here is a write up of what I did in case anyone can try and has better luck.

I am actually developing on a Mac whilst working on this problem and building JOGL turned out to be pretty straightforward.

If you are new to Constellation the you will need to follow the `README.md` to make sure you can compile and run Constellation.

Note that NetBeans 11.3 for the MacOSX was downloaded from http://apache.mirror.serversaustralia.com.au/netbeans/netbeans/11.3/Apache-NetBeans-11.3-bin-macosx.dmg and the JDK from https://cdn.azul.com/zulu/bin/zulu11.37.17-ca-fx-jdk11.0.6-macosx_x64.zip

Once you have Constellation building and running then proceed to the steps mentioned in https://jogamp.org/jogl/doc/HowToBuild.html

The prerequisites mention:

> MacOS and iOS Intel and Arm64
> git ≥ 2.11 provided by Xcode ≥ 8.3.3
> awk is provided by MacOS
> CMake 3.15.2, and install the command line tools
> Mac OS 10.13 or later (note: may not work with earlier releases)
> Xcode 8.3.3 or later for gcc, etc (included in MacOS)

* Note that I was able to get JOGL compiling without installing CMake.
* Note that `7z` is required which I installed via `brew install p7zip`

`ant -Djogl.cg=1 -Dtarget.sourcelevel=1.8 -Dtarget.targetlevel=1.8 -Dbuild.archiveon=true -Dtarget.rt.jar=/path/to/jre/lib/rt.jar`

Note that if I changed the target to be 1.11 or 11 the ant task failed. I tried updating the ant task to accept 11 which then fails during compilation. So I kept it at 1.8 which seemed to work fine.

You can double check everything is working by running the unit tests:

`ant junit.test`

The build file is available at `gluegen/build/gluegen-rt-natives-macosx-universal.jar` and this file can be copied to Constellation's `constellation/CoreDependencies/release/modules/ext/` overriding the existing file.

You will need to do a `clean` `build` of Constellation to make sure you get the file.

Run Constellation and open up a graph from File -> New Graph and go into interactive mode and see the following issue:

![mac offset issue](https://user-images.githubusercontent.com/39325530/79731231-545b5b00-8335-11ea-8a31-18294510de8a.gif)

Note that if you follow the mentioned jomamp forum link above and make the change to `GLCanvas.java` in the AWT package, to compile the change you need to do a `ant clean` before as I've noticed that running a build does not create a new build jar.

Copy the jar over to the Constellation `constellation/CoreDependencies/release/modules/ext/` and see if you have better success.

Assuming the you get to the point where I did (still worth checking as I may have done something wrong) then the next step would be to try and tweak the JOGL library and or follow up with JOGL developers through the forum and see.

**Comment by aldebaran30701** [comment]
Awesome work getting that built and installed! Very weird that it did not fix it completely. 😕 I could be wrong, but it does appear to look like the window is in the correct spot. Is it possible that only the gestures are offset now?

Great work none-the less.

**Comment by arcturus2** [comment]
Thanks @aldebaran30701! I know what your referring to regarding the position looking like it's on the right spot - but on the Mac it looked like this from the beginning. You've reminded me that I should test the fix on Windows to see if it makes any difference so let me do that and get back to you.

**Comment by arcturus2** [comment]
> You've reminded me that I should test the fix on Windows to see if it makes any difference so let me do that and get back to you.

Just realised that building it on a Mac only produces artefacts for the Mac. I would need to do everything on Windows to test it there; so I won't do this @aldebaran30701 sorry.
