### ISSUE TITLE
Ensure default colour scheme does not impact colour blind users

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#46]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Applications need to be compliant so that colour blind users can use our applications.

For starters, the default colour scheme is blue text on a black background and I think this is an issue.

Awaiting formal guidelines before this can be actioned. 
* [x] Check that the current scheme is not suitable for accessibility issues
* [x] Update colour schemes if required.

**Comment by aldebaran30701** [comment]
I feel like the best way to move forward is to do the following.
1. Research colour-blindness compliances
2. Assess current scheme for conformance
3. Quick wins - change graph labels default to white instead of blue. Anything further noted for point 2.
4. Create a scheme using css files to allow easier switching between either a light/dark theme or a high contrast theme. 

This would mean that the ticket relating to .css file merging would need to be done prior to consolidating the theme into one file.
