### ISSUE TITLE
Graph and DAV become unusable after executing a combination of queries

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#460]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Selecting and executing the queries Remove Unused Attributes at the same time as Test Parameters will cause a null pointer exception. After this occurs, other queries will run indefinitely and the graph can no longer be interacted with.

### Steps to Reproduce

1. Select Remove Unused Attributes and test parameters
2. Click Go

**Expected behaviour:** Selected queries run without issue

**Actual behaviour:** Null pointer exception is thrown, queries no longer work and the graph freezes
**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/58677762/80178518-9211f980-863d-11ea-84f9-101bebb32e78.png)

**Comment by formalhaut69** [comment]
In v1.3 the same steps result in a different error message; 
![image](https://user-images.githubusercontent.com/58677762/80323982-81e06100-886d-11ea-83bf-20eee0e2c498.png)

**Comment by aldebaran30701** [comment]
After fixing a stream of issues with the running of both plugins simultaneously, the graph reaches a point where it no longer errors - instead it freezes. 
Running the test parameters plugin from no graph, still results in an error. I've looked into ensuring the attribute exists, and even use .getAttribute() to "refresh" the stored attributeid. This still returns position 24 of an array of length 16. I cannot call .ensure from within StoreGraph because of a cyclic dependency. And would feel odd to call StoreGraph.addAttribute(...) from within StoreGraph , as it is not used from within StoreGraph currently.

Currently I have not got plans to continue on this, as I'd end up just writing smelly code to get something working... 
#477
