### ISSUE TITLE
The Analytic View should read from its state attribute

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#54]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

The Analytic View 2.0 has a state attribute which it writes parameter information to, and saves to the graph. However it currently does not read from that state to restore that parameter information, but rather resets itself whenever graphs change.

### Steps to Reproduce

1. Make a new analytic graph
2. Open the Analytic View
3. Expand the Categories
4. Check the "Betweenness Centrality Analytic"
5. Open a new graph
6. Expand the Categories
7. Check the "Closeness Centrality Analytic"
8. Click on the first graph

**Expected behaviour:** 
The analytic view should show the "Betweenness Centrality Analytic" checked.

**Actual behaviour:**
The analytic view shows the first question selected instead

**Reproduces how often:** 
100%

**Comment by aldebaran30701** [comment]
Am I correct in saying that below, reads a JNode, and obtains the stored parameter information from the graph? 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/state/AnalyticViewStateIoProvider.java#L53-L98
I created a graph, selected and ran some AnalyticView plugins, saved the file and subsequently reloaded them with what appeared to be the correct state.

Could you provide steps to replicate this, or expand on your point regarding the resetting of parameter information and when it occurs. 

One other thing; what is Analytic View 2.0? just the current core Analytic View?

**Comment by arcturus2** [comment]
@aldebaran30701 yep this is the code that looks after the state. Apologies for not providing a decent reproducer. I've just updated the ticket description if you want to have another read?

**Comment by aldebaran30701** [comment]
At this stage, this is my understanding of the issue and how a working implementation would look like.
1. Having a graph opened, and launching the **Analytic View** should pre-select the plugins and parameters checked.  
2. Having multiple graphs opened, and launching the **Analytic View** should pre-select the plugins and parameters checked, and upon switching of graphs, the selected plugins should be different dependent on the state of the graph.
3. Having a graph opened, and selecting a plugin from the already launched **Analytic View** should save that plugin to the graph's state attribute. (Without saving to the graph file until performed by the user.)

As multiple parameters from different categories within the **Analytic View** can be stored in the state, I am suggesting the following. When the **Analytic View** launches and has the plugins pre-selected, either the last iterated plugin selection category is expanded. Or plainly, the default selection of **_"Questions"_** pane. 

Selecting the categories responsible for plugins saved in state will have them load as selected as intended.

I am currently working on a fix and would like to clarify the above behaviour.
Cheers!

**Comment by arcturus2** [comment]
@cygnus-x-1 would you be happy with the above behaviour. This is what I was expecting.

**Comment by aldebaran30701** [comment]
I have a question regarding the "Question" parameter of the AnalyticViewState. @cygnus-x-1 
Is the proposed implementation planned to be utilized with the "save question" option? 
this is what I can grasp - feel free to correct me.
The state handles:
 - Questions store a name and description, along with a list of plugins
 - Questions can be loaded or will automatically appear in a custom question section of the Analytic View
 
What should the state capture if I wanted to ONLY remember the last selected plugins and parameters selected? 
ie. the below method signature would only handle the case of adding an analytic question to the state. If I wanted to use the state to capture the previously selected plugins, what would I pass to the question parameter in order to add it. I've been passing null but it gets ugly with Lists holding multiple null values.
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/state/AnalyticViewState.java#L66
I understand there may have been a change of design, or misunderstanding of what exactly the state should capture. 

Currently, I've got the view reading it's state attribute, selecting the correct plugins and also updating the state attribute when a plugin is deselected. I'm currently working on the remainder of the issue regarding the display of plugin parameters.

**Comment by aldebaran30701** [comment]
This feature is 95% implemented. 
In it's current state, it reads, selects and updates parameters and plugins. The updatedParameters don't show up in the UI for the following reason.
The following lines of code clear any read parameters from the state attribute indefinitely
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java#L112-L121
@arcturus2 OR @cygnus-x-1 Would you happen to know if the above code is correct? I would have thought that if it was checking if a graph met a certain prerequisite, it would either set to default or leave it as it's prescribed value.

Application flow which clears the state loaded.
Graph Loaded -> Analytic View Opened -> updateSelectablePluginsParameters() -> PrerequisiteAttribute iteration -> Clearing of updatedParameters -> Display of default plugin parameters.

**Comment by arcturus2** [comment]
@aldebaran30701 I agree with you. I'm speculating but perhaps this block of code was there as a placeholder to set the UI until it was going to be read from the state. Feel free to modify this section too.

**Comment by aldebaran30701** [comment]
Yes it seems exactly as you mention, that it gets all plugins, and automatically adds the prerequisites to the parameters probably so an empty list was not read. In that case, I will do some additional testing to ensure it is not necessary. Cheers!

**Comment by cygnus-x-1** [comment]
@aldebaran30701 - sorry I haven't responded, I wasn't being notified.

An `AnalyticQuestionDescription` essentially describes a set of `AnalyticPlugin`s whose results can be combined with an `AnalyticAggregator` in order to answer a question in the form of an `AnalyticResult`. All of this could be converted to an `AnalyticQuestion` for use in the Analytic View. There are several examples of this provided with the Analytic View (in the questions package), but the original intention was to allow users to build their own questions from the available plugins/aggregators/result types, and so the `AnalyticViewState` needed to support this. This is also why there is a non-functional options to save a question.

As with other views in Constellation, the `AnalyticViewState` ideally would capture all the information required to restore the last state of the Analytic View. However, an issue we encountered with this model was that the aggregated result set would be required for this to work - and those can be huge and complex. So our plan was to instead store all the information required to be able to re-calculate the analytic. This would be a single `AnalyticQuestionDescription` if a question was in use, or a set of selected plugins if a category was in use. We also had the intention to support multiple concurrent analytics per graph (hence the unimplemented '+' option), and so this would mean a list of questions and/or a list of sets of plugins.

The typical procedure then is to update and write to the graph the `AnalyticViewState` object whenever something significant is selected in the Analytic View UI, and to have a listener attached to that state attribute (in the `AnalyticViewTopComponent`) which would respond whenever that state changed by updating the UI. This pattern is used by all of our (modern) views, such as the Table View 2, Map View, and Scatter Plot.

Finally, the block of code you asked about is for allowing `AnalyticPlugin`s to add listeners to any attributes they rely on, so that they can respond if those attributes change (typically by updating parameters). I don't think this is currently used by any of the unclassified `AnalyticPlugin`s, but it is used ;)

**Comment by aldebaran30701** [comment]
Regarding this last comment, I have a few questions

> There are several examples of this provided with the Analytic View (in the questions package), but the original intention was to allow users to build their own questions from the available plugins/aggregators/result types, and so the AnalyticViewState needed to support this. This is also why there is a non-functional options to save a question.

In saving the question, how would the question be loaded back into the view? ie. if multiple questions are stored, is there a way to select a specific question to load?

> We also had the intention to support multiple concurrent analytics per graph (hence the unimplemented '+' option)

With the multiple tabs "+" the solution in the most recent PR will not satisfy this constraint because there is currently no way to store plugins for a different window. 

> allowing AnalyticPlugins to add listeners to any attributes they rely on, so that they can respond if those attributes change (typically by updating parameters)

Would you know of a workaround or solution to the issue of the event triggers overriding all the stored parameters when it is meant to be adding listeners and changing parameters.

What direction would you suggest I go with this current PR? @cygnus-x-1

**Comment by aldebaran30701** [comment]
@arcturus2 How would you like this handled? 
The state attribute currently satisfies the ticket in the fact that it keeps state of selected plugins and parameters, although does not currently support the format for future implementations.

Would you like the current solution to be altered to support things in the future? Implementation would be extensive in comparison to the current solution.

**Comment by arcturus2** [comment]
Hey @aldebaran30701 thanks for the efforts so far. I'd like to wait to hear back from @cygnus-x-1 first.


>Would you like the current solution to be altered to support things in the future? Implementation would be extensive in comparison to the current solution.

Can you elaborate a bit more on what your thinking?

**Comment by aldebaran30701** [comment]
@arcturus2 
My thoughts are to refactor the way my solution adds to the state attribute. Currently plugins are stored as "X" within the following list structure List<List<X, ...>,List<X, ...>...>
this means refactoring the way it reads from the state also.

The support for the future meaning that the reading and writing of plugin selections would be window specific. This would allow for creating additional tabs of the Analytic View and also having the ability to save a question. Currently I only designed it to run with one tab. 

Another part of the implementation would be to have the change handler of the state attribute update the UI elements. This would be to match other view's implementation style.

**Comment by arcturus2** [comment]
@aldebaran30701 I've had a think and based on past experience, I think that when it comes to reading and writing to the state, making it flexible and future proof is important. I say this because if we want to make a change to the structure of the state later on, it will mean that old graphs floating on the internet will no longer be compatible with the newer version of Constellation. There is a way to solve it by using the graph upgrader framework but we could avoid all of that pain by implementing some flexibility like support for multiple tabs now.

I really appreciate the effort you've put into this so far and it would be ideal if you have time to work on what you proposed too before we merge this to master. Have a think and if you can continue working on this that would be great.

@cygnus-x-1 I'd say that loading and saving options would be a separate task and my preference would be to remove the non-functional "Options" button...that's bad UX. No issues with bringing that back when we are ready to.
