### ISSUE TITLE
Rewrite Find

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#55]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

The Find view has a number of issues. 
1. The three tab interface is a little clumsy and overkill. 
1. The range of advanced find operations need to be expanded (including the requirement for nested boolean logic). 
1. It currently uses deprecated swing editors for attributes (which do not work in all cases) rather than the standard javafx editors used throughout the rest of the application (and defined in the attribute editor module).

All of the above points need to be addressed in the rewrite, the first one particularly with reference to the fact that a new table view should take over some of the functionality that currently lives within find.

**Comment by spjspj** [comment]
The find button should never be greyed out (as it appears to be on the Advanced search)  Instead of greying it out, an 'Invalid search' popup should be displayed instead.

**Comment by antares1470** [comment]
Whoever picks up this ticket should also look to address the work discussed in #852, #856, and #857

**Comment by GammaVel** [comment]
More details and direction is required for this issue based on user requirements

**Comment by Atlas139mkm** [comment]
Testing release candidate 2.4 and these were some things of note I found for when this view gets re-written.

**UI problems**
- If nearby to the bottom of the screen select attributes drop down appears under windows task bar if there are attributes to select. It appears over when there is none. For example when finding nodes then clicking select attributes the drop down will appear under. However for edges it will appear over.
-  Green text stating "# Attribute(s) Selected" does not update properly, giving a false representation of the actual number of selected attributes when changing tabs. 
    - For example:
        - Find: Nodes, Basic Find, Select Attributes: All = 6 Attribute(s) Selected ---- This is all good
        - Swap directly to Find: Links, it still states 6 Attribute(s) Selected however there is actually 0
    - This issue occurs on both Basic Find and Replace tabs when changing what graph element to find and what attributes are selected
- Advanced search: Swapping between Finding Nodes and Transactions the UI elements within the advanced search list are different sizes. Not vital but just something I noticed.

**My UI improvement thoughts** 
- When swapping to the replace tab, the view could probably resize to show the replace with text field. Not vital however it confused me looking at it for the first time not knowing where I would input what I want to replace my search with.
-  "+" and  "-" Buttons in advanced search elements. Might not need to have a "+" button on every advanced search element since they all do the exact same thing, we probably don't need to dynamically add them. 1 "+" button could be added somewhere else to add more elements to the list for simplicity sake. Again not vital just a thought.

**Comment by arcturus2** [comment]
Thank you @Atlas139mkm for your suggestions. These are really useful and fresh ideas we have not considered before. Please keep these suggestions coming.

**Comment by GammaVel** [comment]
I've been taking a look at the new experimental advanced Find and have the following suggestions:

1- Add the total counts back in. The current advanced find reports how many matched. This is only seen in the graph attribute count section which isn't immediately obvious

2 - Can we have a reset option added?  The previous values are being maintained in the same Constellation session and it would be handy to clear it back to defaults.

**Comment by antares1470** [comment]
> I've been taking a look at the new experimental advanced Find and have the following suggestions:
> 
> 1- Add the total counts back in. The current advanced find reports how many matched. This is only seen in the graph attribute count section which isn't immediately obvious
> 
> 2 - Can we have a reset option added? The previous values are being maintained in the same Constellation session and it would be handy to clear it back to defaults.

@GammaVel are you able to clarify what you mean by reset? I don't think I quite follow what you mean

Also could you potentially put each of these suggestions into separate tickets? I think it would be helpful to track the work on these separately (potentially then closing this ticket if there aren't any other immediate issues given it is currently in experimental)

**Comment by GammaVel** [comment]
Thanks @antares1470 for your feedback. The current Find and Replace view has a Reset to default button which is handy when I want to clear my search criteria quickly. With the new Find view I am required to manually clear out what fields I have set or restart Constellation which clears out the text and settings. 
 Here is a screenshot:
![image](https://user-images.githubusercontent.com/83679004/165206954-b1f87f14-c560-4ba5-9e91-03ba14384153.png)

**Comment by GammaVel** [comment]
If it suits you @antares1470 , I will keep adding my feedback to this primary ticket and then break them up if you are happy to raise new issues for them.

Additional feedback:
**Defaults**
The defaults for Attributes are no longer set which initially led me to think that my searches were not working. Turns out it was because I didn't have anything selected in the attributes. Consider automatically adding these back to make it easier and to save mouse clicks.
![image](https://user-images.githubusercontent.com/83679004/165207836-1058ac64-a347-4737-92f9-a7a3d6f0241b.png)

**Plural for node/transaction/edge **etc**
Consider adding back the plural to Node, Transaction, Edge as it is most likely I am interested in more than one value.
![image](https://user-images.githubusercontent.com/83679004/165208427-46354f4b-9844-429b-a1ed-05d3a3ce9d99.png)

**Consider changing In Attributes to With Attributes**
The "In Attributes" text might read better as "With Attributes" and it might be more clear to the users what this is doing. Currently Look For Node in Attributes"  isn't correct as the attributes are a property of the nodes and not the other way around.

**Comment by GammaVel** [comment]
Additional feedback for the Advanced Find:
**Separate out the Match Criteria and the Selection**
The Match Criteria and the Current Selection are close together which initially made me think they were the same field, they are different items. Can some padding be added between them or can the Current selection be added to a new line like it is with the basic find?
![image](https://user-images.githubusercontent.com/83679004/165213058-0cf50d6d-00c9-4eb8-bb3c-1a601c266e1a.png)

**Comment by GammaVel** [comment]
This one is with the advanced find and is a bug - the selected = true is not working as expected:
Here is a gif of the issue:
![selected option](https://user-images.githubusercontent.com/83679004/165230532-c837b016-3c43-479d-b161-208596a248ac.gif)

**Comment by antares1470** [comment]
> Thanks @antares1470 for your feedback. The current Find and Replace view has a Reset to default button which is handy when I want to clear my search criteria quickly. With the new Find view I am required to manually clear out what fields I have set or restart Constellation which clears out the text and settings.

Ok that makes sense. Thanks for the clarification @GammaVel 

I think I agree with most of your suggestions for Basic Find (and Replace). Perhaps though we could change "In Attributes" to "Search in Attributes" or "Find in Attributes" since that might make it clearer what it is talking about. Either way, given how small they are, if we separate these into separate tickets it might be ok to just add them all to the one ticket

> **Alignment of fields**
> Consider matching up the Attribute values with the "Look for" so it is clearer to me as a user what I am searching for

Regarding this advanced find suggestion, could just be me but I think I'm ok with the alignment as it is. I say that as technically those fields at the top don't necessarily align with the ones in each criteria field so for me it might actually make it more confusing (e.g. Match criteria refers to all the different criteria you add, not the type of match you are making such as contains). I think I also like that it separates the criteria panels from the 'global' fields.

Like I said though, just my personal thoughts. Happy for others to disagree

> This one is with the advanced find and is a bug - the selected = true is not working as expected:

Based on your gif, it would appear the boolean logic is flipped so hopefully that is an easy fix

**Comment by GammaVel** [comment]
Thank you @antares1470 for all the awesome feedback on my feedback :-)  Based on your comments I have made 3 new tickets for development consideration - #1695, #1694, #1692. I've spilt this up into the minor screen enhancements (grouped together), bug and a new ticket for the Ignore part as that needs some separate UX thought. Thanks again and let me know if you need any more details!
