### ISSUE TITLE
Switch to using the light weight JOGL panel

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#60]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Switching from using the heavy weight `GLCanvas` to the light weight `GLJPanel` will allow JOGL to inter-operate much better with Swing and Netbeans.

**Comment by sol695510** [comment]
@algol60, @arcturus2 and @cygnus-x-1 recommended I ask you about this issue.

I've uploaded a text document, [JOGL GLJPanel Error.txt](https://github.com/constellation-app/constellation/files/4146244/JOGL.GLJPanel.Error.txt), of the exception that gets thrown when I refactor just the GLCanvas "canvas" variable to a GLJPanel "canvas" variable, since they're both a subclass of java.awt.Component.

![GLCanvas vs  GLJPanel](https://user-images.githubusercontent.com/58677774/73627178-8ac0fc80-469b-11ea-97c1-ef65b477606a.png)

I obtained this after refactoring and enabling the "Debug GL" checkbox in Options.

![Debug GL enabled](https://user-images.githubusercontent.com/58677774/73627111-43d30700-469b-11ea-85cc-b69e95fe97a0.PNG)

![Exception](https://user-images.githubusercontent.com/58677774/73627116-4a617e80-469b-11ea-88b6-a475b1ccf16c.PNG)

If the "Debug GL" option is disabled the pop up doesn't appear but when a new graph is opened nothing is visible but a graph is still being made since if you still build a sphere graph you can open the "Table View" and see the nodes.

@algol60 could you have a look at this and do you know if shaders.txt is still being utilised?

**Comment by doopz** [comment]
@sol695510 I've noticed that you haven't had a response to your questions yet. In the mean time, if you get a chance to then please push your branch so that we could test it out and continue debugging it.

@algol60 you may have missed previous notifications. It would be grateful if you could have a look at this.

**Comment by algol60** [comment]
Definitions: In AWT, each component is rendered and controlled by a native peer component specific to the underlying windowing system. AWT components are "heavyweight" because of their use of OS resources. By contrast, Swing components are often described as "lightweight" because they do not require allocation of native resources in the operating system's windowing toolkit, and are implemented in pure Java. The terms "heavyweight" and "lightweight" refer to the use or not of an underlying OS resource specific to the windowing system, not to the kind of resource being used.

A JOGL GLCanvas is a heavyweight AWT component that can be rendered directly into by JOGL. A GLJPanel is a lightweight Swing component JOGL can't render into; instead, JOGL renders into an offscreen buffer, which is then copied to a JPanel. This means that OpenGL drawing can be mixed with Swing drawing, at the cost of extra resource use (the offscreen buffer) and more time (copying the buffer to the JPanel). A GLJPanel still uses all the OpenGL resources that a GLCanvas does.

Therefore, since we have no use for drawing on a graph using Swing, and a GLJPanel does not provide any other advantages (particularly in its use of graphics resources), there seems to be no point in chasing this problem down.

See:
* https://github.com/JogAmp/jogl/blob/master/src/jogl/classes/com/jogamp/opengl/awt/GLJPanel.java
* https://www.quora.com/What-is-difference-between-GLCanvas-and-GLJPanel
* http://forum.jogamp.org/UI-Artifacts-when-using-GLCanvas-and-GLJpanel-td4029010.html#a4029014
* http://forum.jogamp.org/question-about-the-GLCanvas-and-GLJPanel-td3844025.html#a3863645

**Comment by arcturus2** [comment]
Based on the discussions and update from @algol60 we've agreed to close this as won't do and instead investigate using something like LWJGL mentioned in #404. The latest version of Constellation with improvements to the renderer and advances in Java seem to have helped with Constellation running on more hardware based on current feedback. It also seems to run in VMWare which is something we never had before.
