### ISSUE TITLE
Import window destination dropdown does not refresh as graphs created v2beta5

### ISSUE THREAD

**Issue by forestfairy** [constellation-app/constellation#613]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Import window does not refresh as graphs are created to allow more data to be added to existing graph. To update the dropdown, the import has to be refreshed by closing and reopening, if this is done, previous data runs (and their configuration if yo haven't saved it) is lost.

### Steps to Reproduce

1. Open Constellation
2. File>import
3. press green plus sign to navigate to required dataset
4. Upload data from dataset, graph is automatically created 
2. Upload second dataset with new attributes 

**Expected behaviour:** 
As datasets are added to the analysis, it would be expected that the "destination" drop-down would automatically refresh to include graphs as they are created

**Actual behaviour:** 
For a new dataset to be added in this manner, the import window needs to be closed and reopened to refresh. This also causes the existing dataset and attribute setting to be lost

**Reproduces how often:** 
100%

### Additional Information

Likelihood 100%
Consequences medium (annoying rather than catastrophic)

**Comment by aldebaran30701** [comment]
My thoughts on this are as follows:
We need to trigger an update of the dialog's drop down menu whenever a new graph is added.
I'd like to add a listening pattern similar to one implemented in the `QualityControlAutoVetterListener.java`
I would have to trigger it upon creation of a new graph. The reason for this is because the dialog which houses the delimited file importer does not use the attribute listening framework like I know it. ie. not via TopComponent. I don't however like the idea of having to trigger it from inside creation of a graph. I'd rather have it listening in on it.

I'd love to know if @cygnus-x-1 @sirius-1 @arcturus2 know of a listening framework currently in place that can do the above.

**Comment by arcturus2** [comment]
@aldebaran30701 I'd prefer looking to make the delimited file importer be refactored to use the attribute listening framework. I agree that having special logic in the graph creation to trigger the dialog drop down list is undesirable and start taking us down a slippery slope.

My suggestion would be if @aldebaran30701 could do a feasibility study to see how difficult it is to include the attribute listening framework to the dialog and if it is "easy" then consider implementing it or else part this requirement.

The delimited file importer needs an overhaul so if it is difficult to include the attribute listening framework then maybe we collate all of the requirements, sit together as a group and design it and address the refactor of the delimited file importer.
