### ISSUE TITLE
The Hop-out plugin breaks when both 'incoming' and 'outgoing' are selected.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#681]
### Description

Using the hop-out plugin with 'incoming' and 'outgoing' selected (but 'undirected' not selected) results in the plugin failing to hop-out. It does work if only one of those options are selected, or if you have 'undirected' selected in addition.

### Steps to Reproduce
As above

**Expected behaviour:** [What you expect to happen]
The plugin should hop out when 'incoming' and 'outgoing' are selected.

**Actual behaviour:** [What actually happens]
The plugin does not hop out when 'incoming' and 'outgoing' are selected.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by serpens24** [comment]
I have attempted to reproduce this issue using Constellation Core 11.3-6b879cb782eaa4f13a731aff82eada11289a66f7 (2020-07-23) and been unable to reproduce .. see image below:

![HopOut](https://user-images.githubusercontent.com/58677108/88508565-4301a900-d01e-11ea-952a-bb70ff0d1b56.gif)

Unsure if there is anything I am missing here, but given this behaviour perhaps the issue is now resolved @arcturus2
