### ISSUE TITLE
Forward slash allowed in graphs name, causes errors if used.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#698]
### Description
Attempting to rename the graph to a name including a "/" character results in the following error:
Cannont rename file ____.star on MemoryFileSystem

### Steps to Reproduce

1. Make a graph
2. Rename graph name to include a "/".

**Expected behaviour:** [What you expect to happen]
Constellation should not allow "/" in graph names, this should be handled identically to other illegal inputs.

**Actual behaviour:** [What actually happens]
Constellation allows "/" in graph names and then errors.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown.

**Comment by serpens24** [comment]
I attempted to reproduce this using v2.0.0 and instead of getting the error listed found that the star file was created, but '/' was used as a directory seperator, hence entering the filename "aaaa/bbbb.star" resulted in a file called "bbbb.star" being created in a new "aaaa" folder (relative to parent directory).

I still think this behaviour is an issue as windows itslef doesn't allow slashes in filenames ... seee the image below when creating a new file:

![image](https://user-images.githubusercontent.com/58677108/87999963-8dc18380-cb3b-11ea-9b62-bb7d8d7e3e4c.png)

Refer also to https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file:
![image](https://user-images.githubusercontent.com/58677108/88000041-ce210180-cb3b-11ea-93ce-4e5376d775bb.png)


Linux is more forgiving with filenames, as it does allow escaping, but generally this is not preferred ...
https://www.cyberciti.biz/faq/linuxunix-rules-for-naming-file-and-directory-names/
![image](https://user-images.githubusercontent.com/58677108/88000305-72a34380-cb3c-11ea-9892-79a747c4093b.png)

I'm not as familair with Mac (OK - I've never even touched one) although the following link suggests MAC/OSX is more akin to Linux than Windows: https://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os.  Reading through this analysis it tries to identify a character set for use in filenames to generally avoid issues, the follwing "concludsion is made":
![image](https://user-images.githubusercontent.com/58677108/88000578-23a9de00-cb3d-11ea-9e25-0f41bdf0491c.png)

This recomendation would suggest only allowing specific characters when creating filenames - AND would allow a regex type validation ...  This character set would be the set of characters I would 'generally' use, however characters such as '()+=' etc would also be used at times, so I suspect this reccomendation is too restrictive.

I think our ultimate solution needs to be to settle on a character set that is valid and construct a regex validation to validate proposed filenames against this character set .... however we would also need to consider existing filenames or files renamed on filesystems outside of Constellation ... ie if a user manually inserted unsupported characters using a file rename operation (ie windows explorer, select file and rename).

I think my default position would be to use the Windows approved character set - ie everything apart from "<>:"/\|?*" which makes files suitable for windows, but possibly a little more restrictive than linux and OSX would generally allow ...

@arcturus2 thoughts ?

**Comment by arcturus2** [comment]
@serpens24 thank you for the write up. If we can avoid having OS dependent code then the better in my view too so happy to just use the allowed characters for Windows to start with. If it ever becomes a requirement to save graphs in sub folders (which would be neat) then we can revisit this. Catching the error right now is better than letting it fail.

**Comment by formalhaut69** [comment]
Couldn't get the error mentioned in the issue but I got a ClassCastException when putting a "/" at the end of the file name when saving. The "/" will make a new folder with the name of whatever is on the left half of the "/" and the .star file will be named whatever is on the right half. Probably broke because I forced it to name it an empty string. 
![image](https://user-images.githubusercontent.com/58677762/88122094-d5f9a800-cc06-11ea-8eae-448cc51d2141.png)
