### ISSUE TITLE
Experimental -> Tools -> Add Banner: Exception

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#721]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Adding a banner causes the below exception

```
java.lang.Exception: No I/O provider found for object type au.gov.asd.tac.constellation.graph.schema.visual.attribute.objects.Banner, attribute ImmutableAttribute[id=57;type=banner;label=banner;description=banner;elementType=Metadata;defaultValue=null]
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonWriter.writeElements(GraphJsonWriter.java:386)
[catch] at au.gov.asd.tac.constellation.graph.file.io.GraphJsonWriter.writeGraphToStream(GraphJsonWriter.java:261)
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonWriter.writeGraphToZip(GraphJsonWriter.java:168)
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonWriter.writeGraphToZip(GraphJsonWriter.java:144)
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonWriter.writeGraphToZip(GraphJsonWriter.java:135)
	at au.gov.asd.tac.constellation.graph.interaction.plugins.io.AutosaveGraphPlugin.execute(AutosaveGraphPlugin.java:94)
	at au.gov.asd.tac.constellation.plugins.templates.SimplePlugin.run(SimplePlugin.java:68)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.executePluginNow(DefaultPluginEnvironment.java:219)
	at au.gov.asd.tac.constellation.plugins.PluginExecution.executeNow(PluginExecution.java:310)
	at au.gov.asd.tac.constellation.graph.interaction.plugins.io.Autosaver$1.run(Autosaver.java:113)

```
### Steps to Reproduce

1. New graph -> draw mode, add 3 nodes, select 1
2. Add banner

**Expected behaviour:** A banner to be added

**Actual behaviour:** Exception, and that is all

**Reproduces how often:** 30%

### Additional Information

Found using .exe v2.0 rc2

**Comment by cygnus-x-1** [comment]
This should be easy to fix - looks like we just need to write a `BannerIOProvider` class, or add a @ServiceProvider annotation if one already exists.

**Comment by Auriga2** [comment]
@cygnus-x-1: Not sure where this banner is added. Can it be seen in the graph? I got the exception only once, in the exe, but the other times nothing seems to actually happen. Also there is already a `BannerIOProvider` class with  `@Serviceprovider` annotation.
![image](https://user-images.githubusercontent.com/64826928/88141152-2f2b0100-cc32-11ea-9e45-9810831bcc75.png)

**Comment by arcturus2** [comment]
> Not sure where this banner is added. Can it be seen in the graph?

@Auriga2 Yes,  the banner is meant to appear on the top and the bottom of the graph as a thin strip with text. Perhaps this stopped working when the renderer framework was updated which was done over 2 years now. This is still good to fix though it will likey require some OpenGL experience.

@aldebaran30701 I wasn't getting any exception when I followed your steps.

**Comment by aldebaran30701** [comment]
@arcturus2 I'd be adding a banner, and then a few seconds later I noted the exception icon. It could be linked to autosave as it is an IO Provider error? Odd that it has the correct class but errors...

**Comment by arcturus2** [comment]
> It could be linked to autosave as it is an IO Provider error?

Yes you are correct. I saw the error after doing the save. Thank you for the clarification.

**Comment by formalhaut69** [comment]
This issue is really odd. I've done a bit of analysis and I've noticed that the BannerIOProvider is being registered properly because you can see it in the list of all of the providers within the getProviders() method in AbstractGraphIOProvider.
![image](https://user-images.githubusercontent.com/58677762/88629046-ef5e9080-d0ed-11ea-81a6-4f5b92a05f51.png)

But whats strange is that when you call the getProviders() method from another class, for example in the GraphJsonWriter constructor the BannerIOProvider is not returned. I'll do some more analysis though and see what else I can find.

**Comment by arcturus2** [comment]
Good debugging @formalhaut69. This is really an interesting and facinaing example. Did you find out any more? I'd be happy to help troubleshoot this one - just let me know where you get up to.

**Comment by formalhaut69** [comment]
> 
> 
> Good debugging @formalhaut69. This is really an interesting and fascinating example. Did you find out any more? I'd be happy to help troubleshoot this one - just let me know where you get up to.

@arcturus2 I figured out that the bannerIOProvider is actually being returned but it's name was set incorrectly as "color" so you end up with two "color"s in the list of providers. Changed it to this; 

`@Override
    public String getName() {
        return BannerAttributeDescription.ATTRIBUTE_NAME;
    }`

It didn't fix the issue though. I have a feeling that something that links the banner class to the BannerIOProvider class is either missing completely or broken but I don't know enough about serviceIOProviders to know what it is. What would you need to add to the banner class so that it knows the BannerIOProvider is it's serviceIOProvider?

**Comment by arcturus2** [comment]
@formalhaut69 it turns out there is a hidden requirement for this to work. In the `Banner` class, you need to implement `convertFromString()`. I did a quick test and was able to see the exception go away when I followed something similar to the `Blaze` class. I also changed `BannerAttributeDescription` to use `AbstractObjectAttributeDescription<Banner>` so is that enough information to go on with?

**Comment by formalhaut69** [comment]
> 
> 
> @formalhaut69 it turns out there is a hidden requirement for this to work. In the `Banner` class, you need to implement `convertFromString()`. I did a quick test and was able to see the exception go away when I followed something similar to the `Blaze` class. I also changed `BannerAttributeDescription` to use `AbstractObjectAttributeDescription<Banner>` so is that enough information to go on with?

Cool, thanks for investigating this issue a bit more @arcturus2.

**Comment by cygnus-x-1** [comment]
I don't think you necessarily need to implement `convertFromString`. Broadly, for an `IOProvider` to work, you need to define a way to serialize an object (in this case a `Banner`) to and from JSON in the `IOProvider` class. I suspect `convertToString` is offloading the work to the `Banner` class in this case, but it could just as easily be done in the `IOProvider` class.
