### ISSUE TITLE
Draw-mode Directed Transactions incorrect behaviour

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#723]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Drawing from one vertex to another should not draw a direction indicator in both modes. It should only draw it in "draw directed transactions" mode. 

![directed mode2](https://user-images.githubusercontent.com/58677759/87748359-d1af4280-c834-11ea-89ba-e111c9be37f5.gif)

### Steps to Reproduce

1. make 2 vertices
2. draw mode with directed transaction
3. draw mode without directed transaction

**Expected behaviour:** draw one arrow-ed transaction, draw one un-directed transaction 

**Actual behaviour:** both transactions are directed

**Reproduces how often:** 100

**Comment by aldebaran30701** [comment]
I did some research into this, and ended up in the low level code of `StoreGraph.java`. The plugin to add a transaction `CreateTransactionPlugin.java` seems to be functioning fine, as when I called the plugin with a hard-coded false value to always draw an un-directed transaction - it still drew directed transactions. 
I followed the code deeper and could not find out what was causing this odd behaviour. When I initially hard-coded the value as `false`, the transactions were correct and not directed. but a clean and build seemed to stop this happening. I'm not sure if I found some odd race condition but could not replicate it.

**Comment by aldebaran30701** [comment]
@antares1470 I have a query as to this commit, it seems to be causing this issue. https://github.com/constellation-app/constellation/commit/2ab65c6a4c9de91a5953cd7174957f17d24db06f
@Auriga2 has been working on a fix but we are not convinced that it will not cause an issue with the original reason for your commit.
 IE. What do you think will fix this, but not break your fix.

**Comment by antares1470** [comment]
@aldebaran30701 Previously, null and empty types were treated separately. Since treating them the same (which makes sense), we were seeing some unexpected behaviour with blank types and the commit you highlighted was the fix we came up with for that. What I didn't consider though was draw mode draws unknown type transactions (the default type) and so it is now altering the direction to the default directedness of the unknown type (true in this instance).

This was clearly an oversight on my end and you are right in that reverting my commit would fix this issue.

**Comment by aldebaran30701** [comment]
>seeing some unexpected behaviour with blank types 

Is this something I can replicate on my end? I wouldn't know where to start with looking for a fix that satisfies both. Plus I'm not sure the extent of the problem if we were to revert your commit - which understandably, I will leave the ball in your court for.

**Comment by antares1470** [comment]
To replicate, create a unit test with a few transactions with empty string types. Run merge transactions so that some of them merge and then complete schema. You'll see a change in transaction ids that previously only happened if the type was unknown (the default).

In the scheme of things though, it's not that big a problem (since you're probably unlikely to want to have blank types) and so I would go ahead and revert that commit. If the blank types issue becomes more of a serious problem, we can address it later.
@aldebaran30701 @Auriga2
