### ISSUE TITLE
Closing graph doesn't clear content bubbles in Conversation View.  

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#727]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Closing graph doesn't clear content bubbles in Conversation View. 

### Steps to Reproduce

1. Open a graph with content attributes (conversation bubbles).
2. Open Conversation View.
3. Close graph.

**Expected behaviour:** Content bubbles cleared from Conversation View.

**Actual behaviour:** Content bubbles not cleared from Conversation View.

**Reproduces how often:** 100%
![ConversationView_error](https://user-images.githubusercontent.com/54261086/87900094-a7f55600-ca96-11ea-9cac-d08e44798215.PNG)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by formalhaut69** [comment]
A solution to this issue is to get the Update method on line 282 in the Conversation class to run which should clear all the messages in the view. An onGraphClose method should be added to the ConversationViewTopComponent class which should call the update method somehow. I couldn't get this to work though because ConversationViewTopComponent doesn't have access to the update method. The closest I could get was to run conversation.getGraphUpdateManager().testCurrentGraph(); which should test to see if the conversation view needs updating because the graph has changed. It should update it because the graph is no longer open, this worked initially but after a clean and build it no longer worked. Not sure why, perhaps it was some odd race condition where the graph had yet to finish closing when conversation was supposed to update so the application decided it didn't need to refresh the view.

**Comment by aldebaran30701** [comment]
I've done some analysis on this also. I tried to call messageUpdater which is a thread as mentioned `Update method on line 282`
I linked it up with the `.dependOn(graphUpdateController.getNewGraphUpdateComponent())` event which successfully calls the `messageUpdater` Thread. What occurred was a deadlock. I switched to using `Platform.runLater(..)` in an attempt to rectify the lock. It still locked up so I instead only called `allMessages..clear()` which did not seem to refresh the UI.
I couldn't manage to "refresh" the UI.

@sirius-1 I was wondering if you would be able to explain how we can monitor a graph closed event or something similar to link with a method that will reset the view to show no selections.

I did also try and run a deselect all plugin, on graph closed. This should have triggered an update to clear the view - but did not. Possibly because of the timing of it even with a future.

**Comment by Nova-2119** [comment]
Sorry I forgot to update this, I picked it up yesterday arvo.
Thanks @formalhaut69 and @aldebaran30701 for your previous work on this ticket, it helped me get to grips with what was happening way quicker than starting from scratch!

Most of the updating seemed to be getting done in Conversation. So I chucked some breakpoints in there to see what gets hit after various activites (opening a graph, modify a graph, switching graphs etc). A bunch of stuff was getting hit for pretty much everything except when you close the graph. Nothing got called when you close the graph without another graph already open.

So I went and had a look in GraphUpdateContoller to see what closing a graph might trigger and why there is a distinction between closing the only graph vs closing a graph when there is another open. Here is noticed the handleNullGraph() method and that the only thing that cares about it is newGraphUpdateComponent.
Switching back to Conversation we see that nothing is watching that component, and a closer look at what is being watched reveals that nothing cares about what happens when a graph is closed, and the difference in behaviour is because it is being triggered by the forced switch to the other open graph, not the closure itself. Hence when you close a graph by itself nothing happens. This is in line with what @aldebaran30701 said in the previous comment.

To combat this I have added a new updateComponent which depends on newGraphUpdateComponent and just returns whether or not the graph is null. I then added this as a dependency to some of the other updateComponents to try and mimc the behaviour that occurs when a new (read: empty) graph is opened, as we would expect the view to look mostly the same.

This is when I ran into the deadlock described by @aldebaran30701 . Turns out in some of the updateComponents there is a CountDownLatch triggered which stops threads from progressing beyond the next call to latch.await() unless a specified number of latch.countDown() are called beforehand. It only ever asks for one latch.countDown() to be called but this is after a call to a method that takes graph as a parameter.
These methods were all unable to accept a null graph argument and i'm pretty sure were erroring behind the scenes, with the error being stopped from appearing by the thread lock (I think, my knowledge of threads locking and such things isn't great).

I went through and made all of these methods compatible with a null graph argument and that seems to have stopped the locking problem and fixed the issue :). Just doing a couple more tests and will then put up a pull request.
