### ISSUE TITLE
Split nodes plugin adds new nodes on top of each other.

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#810]
### Description
In a `Sphere Graph`, if you do not select the `Split on All Occurrences` and run the `Split nodes plugin` multiple times on the same node to split further, OR on different nodes to split them, all the new nodes are added on top of each other. I could not recreate this behaviour on a graph drawn using draw mode.

### Steps to Reproduce

1. Create a Sphere graph ( Experimental->Build Graph->Sphere Graph Builder)
2. Open Attribute Editor and rename some nodes to a delimited string such as `abc;def;ghi;jkl`
3. Open up Data Access View and go to Split Nodes plugin
4. Set the `split character` as `;` and leave the `Split on All Occurrences` option unchecked
5. Ensure the renamed node/s is/are selected and run the plugin few times

**Expected behaviour:** New nodes are not overlapping

**Actual behaviour:**New nodes are  added on top of each other

**Reproduces how often:** 100%

### Additional Information
Same behaviour irrespective of the `Split Nodes into same level` option added in https://github.com/constellation-app/constellation/pull/773

**Comment by Auriga2** [comment]
![splitnodes](https://user-images.githubusercontent.com/64826928/91143549-d8fa2380-e6f1-11ea-84c1-38f389f1e64a.gif)

**Comment by aldebaran30701** [comment]
I've just tested this and it seems that they now do not stack on top of each other - unless I have failed to replicate this.
Mine offset by a small amount but still overlap. I would think that this is the best way forward as the user will see there is 3 nodes stacked and clustered.
![splitnodes](https://user-images.githubusercontent.com/58677759/106530434-3cf40400-653c-11eb-8731-b80bb080a2d1.gif)

Noted that this has been tested by other users who still report the problem - just more infrequently. 
To mention also, is that commenting out the code responsible for arranging after the split is done, results in the nodes stacking completely on top.

This leads me to believe that the issue is with one of the three arrangements.
```
PluginExecutor.startWith(ArrangementPluginRegistry.GRID_COMPOSITE)
                .followedBy(ArrangementPluginRegistry.PENDANTS)
                .followedBy(ArrangementPluginRegistry.UNCOLLIDE);
```
I did a little digging into the uncollide behaviour but could not narrow it down. Even uncommenting the Uncollide part of the `PluginExecution` still resulted in similar behaviour.

**Comment by Auriga2** [comment]
Agree, it seems fixed now. But if a single node can be splitted multiple times, after like the 6th splitting they tend to position on top of each other, but I guess that can be ignored because the first few implies they are overlapping, and the user can rearrange to see them clearly?
![splitnodes](https://user-images.githubusercontent.com/64826928/124551256-061a7500-de71-11eb-9087-6f1c07a14ad1.gif)

**Comment by antares1470** [comment]
> 
> Agree, it seems fixed now. But if a single node can be splitted multiple times, after like the 6th splitting they tend to position on top of each other, but I guess that can be ignored because the first few implies they are overlapping, and the user can rearrange to see them clearly?

I think if it doesn't happen until the 6th splitting or so then that is likely a rather extreme case, especially if a user isn't arranging nodes in between. As mentioned, it's also fairly easy to get around (re-arrange the nodes) so based on all that, I think I'm happy to close this. Is that ok @Auriga2?

**Comment by Auriga2** [comment]
Yes agree, closed.
