### ISSUE TITLE
Memory leak related to the graph

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#837]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

During testing and profiling of the application, it was noticed that the graph now has a memory leak. 
Garbage collection does not clean up the object.

### Steps to Reproduce

1. Open Constellation
2. Open new graph
3. Close new graph

**Expected behaviour:** No graphs held within memory

**Actual behaviour:** All graphs stay in memory and cannot be garbage-collected.

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by Nova-2119** [comment]
So I think I have found the leak.
The visualGraphTopComponent doesnt get cleaned when a graph is closed. Instead it gets cleaned when you open the next graph. This also stops the VisualManager from getting cleaned. Most of the resources associated with the graph are tied to this somehow, so I think this explains why there is very little memory recovery when you close graph.
It also explains why the affect doesn't "stack" if you open multiple graphs, and then close them all, the memory retained is the same as when the last graph was open. As long as another graph is open the finalizer is called. If no other graph is open the finalizer is called next time you open a graph.

After some reading about memory leaks in Java my suspicions is that this due to all the static variables in the class. I'm not entirely convinced yet, but I think this is stopping the finalizer getting called on the last instance of the class? The class itself is being used by Netbeans code, so we can't really do anything up the stack to try and convince it to Garbage it.

Hence i'm thinking I will will write a method that clears all of the non-static variables and call this when componentClosed is called. I think this will minimise its memory usage and might release references that allow other classes like the visualManager to finalise. Will comment hear on how it goes!

**Comment by Nova-2119** [comment]
For the record, the profiler did not help at all and if anything hindered me! After doing some reading I saw that overriding finalizer can cause memory leaks. So I did search for finalizer and found that VisualTopComponent, VisualManager etc all overwrite it.
This cause me to stumble upon MemoryManager, a class in Constellation specifically for developers to help them debug memory leaks 🕺.
Using this as some debug statements I figured out that the top component and manager arnt getting finalized when the graph is closed. I then did some static analysis to try and figure out what memory it might be using and compared this to some before and after heap dumps I had made earlier to see if the variables they have correspond to the classes hanging around in memory. Its only a very rough sanity check but it seems plausible and it fits with the behaviour of the leak.

**Comment by Nova-2119** [comment]
Hmm, on further investigation it seems the VisualManager and VisualAccess both cleaned up one you force a garbage collect after the graph had been closed.

@aldebaran30701 there is still increased memory usage after performing the cleanup, but its not a huge amount. Can you confirm for me that the current behaviour around memory usage is what you observed when creating the ticket.

**Comment by aldebaran30701** [comment]
@Nova-2119 I just added the ticket, It was noted from @arcturus2 during some testing that this was occurring. I haven't tried it previously, but I can give it a go to see if I can replicate it.

**Comment by Nova-2119** [comment]
So from what I can see memory usage increases from 78,567,630 to 96,745,384 once you open and close a 100,000 Node graph and perform garbage collection.

It's not ideal that it doesn't always perform the garbage collect (even if we click the memory button to try and force it) but given it will perform it when needed are we worried about a memory increase of this size?
@arcturus2 @antares1470
