### ISSUE TITLE
Fix rendering of buttons and menu options

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#866]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Menu options in views are not obvious because they don't look like something you can click on. For example refer to the "Options" menu on the top left of the Data Access View. Same thing for menu options in the Map view.

These are JavaFX CSS type fixes.

**Comment by cygnus-x-1** [comment]
An example of this is the Delimited File Importer Options Menu, which contains options for saving and loading templates, which we've seen many users miss altogether.

**Comment by serpens24** [comment]
The only real way to address this issue is to roll through different views and look for buttons that are not distinguishable. The examples cited by @antares1470  and @cygnus-x-1 are just two examples.

Its also worth noting that both the 'Data Access View' and 'Delimited File Import' view have an 'Options' menu at the top left that is not obvious - but its owrth noting the actual shading of these two views is different, see image below where the 'Delimited File Importer' window has a darker top bar than the Data Access View.

I don't propose to make this consistant at this point unless it falls out in ensuring the button colorations are unique.

![image](https://user-images.githubusercontent.com/58677108/105116406-a0cd0480-5b1a-11eb-8387-ce16e9910a74.png)

**Comment by serpens24** [comment]
Ehile the colors below are not a reccomendation, they were used to validate the reason the Option buttons were not easily identifed - ultimately, the reason is that these buttons are menubar buttons which by default share the same look as the underlying menubar.

Hence the approach needs to be to change the colour of the .menu-button item in the css styles.

![image](https://user-images.githubusercontent.com/58677108/105131358-ad605580-5b38-11eb-8ae5-2f91cb70227e.png)
