### ISSUE TITLE
Preset blaze colours

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#869]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be handy to be able to change/add to the list of preset blaze colours. Every time you want to use a different colour not in the existing preset list, you have to click through a few menus to find the colour you are looking for. It would probably save a bit of time if you could make a list of "favourites" that are available to select from either the blaze menu in the toolbar at the top of Constellation or by right clicking and hovering over "Blazes".

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by serpens24** [comment]
@antares1470 - interested in your thoughts

I've been expermineting a bit with what can be done here, my current thought is to provide the abiltiy to preset some custom colours that will show up in the selection menu ... I've added 5, and currently they are in the top level blaze menu, but they could sit in a nested Custom color menu:
See below:
![image](https://user-images.githubusercontent.com/58677108/100396493-25f4e980-3095-11eb-86df-3d4be0202e96.png)

The Constellation/Graph Options panel seems the correct place to be able to configure these, ie:

![image](https://user-images.githubusercontent.com/58677108/100396610-a1569b00-3095-11eb-9cd6-5eb23da1a84b.png)

In tis example, pressing the 'Set Colour' button would launch the colour chooser and let users selecxt the colour. Like the other Blaze dfefaults these could be stored in a userts config somewhere ..... the textfield would allow a colour name to be supplied, which would be displayed in the menu (forst image).

Note, I suspect with the small size PNGs used in the menu to display the coloured blaze icon I should be able to bang up a quyick method that takes a template blaze ixcon png and transforms the colour to match that selected, so that the menu icons match the selected colour.

I was proposing a hard coded 5 custom colours in the first case, but we could get tricky and provide a dynamic list of up to 16 or similar which limits which ones are displayed in the menu.

None of thewse changes would require trhe existing Add Custom Blaze to be removed, and in fact this widget may be able to be reused for the selection of custom colour (colour picker) mentioned above.

**Comment by antares1470** [comment]
> @antares1470 - interested in your thoughts

@serpens24 Sorry for not getting back sooner. I reckon what you've proposed I think is a good way forward for this. I think 5 custom colours in the first instance would be enough and we can also always extend that further if needed.

For the menu items, I reckon it would be good to be able to make it clear that the blaze colour they can select is a custom colour. I think adding the sub-menu option would also be the better option to help distinguish that. You could also then a menu item at the bottom of the sub-menu which goes straight to the options panel to change the custom blaze colours and names.

Those are just my thoughts though.
