### ISSUE TITLE
Welcome tab

### ISSUE THREAD

**Issue by imranraza83** [constellation-app/constellation#9]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Create a Welcome tab something similar to [SAAY2689719071515300.pdf](https://github.com/constellation-app/constellation/files/3395047/SAAY2689719071515300.pdf).

The idea would be that new users can have tiled buttons to do typical things like:
* Open a new graph
* Import a CSV file
* Open an existing graph

Ideally the implementation of the welcome tab should be extensible to override the buttons with different features.

**Comment by canis-majoris-42** [comment]
Michael Sung's going to start design mockups next week.

**Comment by arcturus2** [comment]
Here are mock ups of what we are looking to do @Delphinus8821. We might look at the dark theme first though :-)

There is also a branch called `welcome_page_update` that has started this work and the idea here regarding implementation would be so that clicking on a button should do an action. For example, a button to open a new graph, a button to open the imported delimited file importer etc. Note that these actions need to be implemented in a manner so that we can override what goes in there from another module suite. We do this using the `ServiceProvider` annotation.

With regards to opening recent files, I have some ideas about creating a preview of the graph but we can do that once the other bits look right.

**Dark Theme**
![welcome2 (2)](https://user-images.githubusercontent.com/39325530/98179013-ef262a80-1f51-11eb-85c5-d1a09d659915.png)

**Light Theme**
![welcome2 – 1](https://user-images.githubusercontent.com/39325530/98179016-f0575780-1f51-11eb-8d7c-47381ccc29b6.png)

**Comment by cygnus-x-1** [comment]
Some thoughts;
- the tutorial page should not launch on startup alongside the welcome page (the welcome page provides a link to it) and there should be an option in the options menu for whether or not to launch the welcome page on startup (replace the tutorial page option). Also, should the tutorial page just become a 'what's new' page?
- as identified in [this issue](https://github.com/constellation-app/constellation/issues/932), the welcome page is not responsive.
- there should be an option to start with a new empty graph in selection mode, as often the workflow will be to use the DAV to import some nodes and chain from there.
- i'd suggest adding an option to import from jdbc alongside the delimiited file import option.
- the link to the documentation should lead to a something more welcoming (perhaps a on page 'getting started' guide), rather than the confronting list of stuff it currently gives you.
- if possible, the 'provide feedback' link should present a template more aligned with providing feedback (as oppose to the regular bug report / feature request template).
