### ISSUE TITLE
Delimited File Importer 'Row' column cannot be used

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#98]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

The auto-generated 'Row' column in the file preview pane cannot be assigned an attribute (this worked at one point in the past).

### Steps to Reproduce

1. Open the Delimited File Importer tool and choose a file.
2. Drag the source.Identifier attribute onto the 'Row' column.
3. Click the Import button.

**Expected behaviour:** [What you expect to happen]

There should be n nodes on your graph where n is the number of rows in your delimited file.

**Actual behaviour:** [What actually happens]

There is one node on your graph, as the 'Row' column was ignored and so all nodes were collapsed into one due to the missing primary key values.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by serpens24** [comment]
The issue here is the **setValue** function in the class **ImportAttributeDefinition**.

this function has an if else block testing the member variable **columnIndex**.
The value of **columnIndex** for attributes tied to columns in the source data run from 0-x where x is the total columns -1.
The value of **columnIndex** for attributes not tied to columns is ATTRIBUTE_NOT_ASSIGNED_TO_COLUMN.
However if the user selected the **Row** column in the importer, this is a generated column and doesn't exist in source data, it returns a **columnIndex** value of -1. As can be seen, this value falls through the ifs and hence a null value is returned as the column value.

To fix, modify the **setValue** function to take a fourth parameter **rowIndex** which is passed the index of the row. An else condition can then be added to use this value. Note this else condition will test for -1, hence if by some means a value other than -1, ATTRIBUTE_NOT_ASSIGNED_TO_COLUMN, or the value of a real column in the importer, then a null would be returned.

This function is called 4 times, all in the **processVertices** or **processTransactions** methods within **ImportDelimitedPlugin**. These are all sitting in loops running through the rows of data, so its easy to determine the row index.

Have tested this, and now when I selec tthe Row column for either an identifer, or some other field, the displayed numerical value is added to the graph.
