### ISSUE TITLE
High memory use deleting nodes

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#980]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The recent performance improvements in v2 are great allowing graphs to be opened so much quicker. The implementation involved multi-threading and a conscious decision to use more memory to allow for real parallelism.

It looks like deleting nodes of a graph is causing the graph labels code to run which is spiking up memory use (as a side affect of the above performance changes).

Why should deleting nodes require a complete re-render? Ideally deleting nodes should not have to call the code creating the graph top/bottom labels to be called.

Could some caching be used?

![memory increasing when deleting nodes](https://user-images.githubusercontent.com/39325530/108937385-c1045c00-76a2-11eb-9ad2-317a9b5fc5ab.gif)

Note that if I call the GC to run it will reduce memory used. Until the memory is released however, Constellation becomes a bit sluggish as the JVM deals with the memory its trying to manage with these quick successions of graph interactions.

In the gif, the response time to delete nodes took a while as well. This might be due to the slower machine I'm on and running profiling as well.

### Steps to Reproduce

1. New Sphere Graph of 10,000 nodes and 5000 transactions
2. Tree arrange
3. Observed the memory was idling at 413 MB / 500MB
4. Select some nodes with transactions and delete them
5. Repeat the process
6. Observed the memory jumps to 3.5 GB / 4 GB

**Expected behaviour:** [What you expect to happen]
Memory use should not spike very high when deleting nodes. Certainly the undo/redo stuff will take up some memory and running the delete plugin should too but nothing crazy.

**Actual behaviour:** [What actually happens]
Memory spikes and causes application to become slow/sluggish.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by Nova-2119** [comment]
High memory is due to the graph being rendered to the screen after deleting nodes.

It may seem excessive at first glance to rerender the whole graph after deleting some nodes, however the current change framework and implementation of NodeLabelBatcher do not really allow us to avoid this fate.
The operation is therefore the same as when opening a graph and any changes made, for instance to reduce memory usage at the expense of speed will affect both.

I have made a change tied to this ticket to try and stop repetition of visualChanges being rendered to the graph. In particular this should roughly half the time it takes to delete nodes as previously deleting nodes would trigger two separate changes that would each cause a vertices_Rebuild (structural change and node visibility change). Now the second of these will be eliminated by the first and the vertices will only be rebuilt once.


In future there are multiple options for improving the performance of deleting nodes. However each is a large job:

1) Improve the performance of renderTextAsLigatures as noted in https://github.com/constellation-app/constellation/issues/984 . This will make rebuilding vertices quicker and hence make deleting nodes quicker. Should this be really succesful we may be able to eliminate or dramatically reduce the multi-threading present in NodeLabelBatcher and hence reduce memory usage aswell.

2) Refactor change framework. Currently the change framework relies heavily on graph modification counters to register when a change is made to the graph. However in many cases by the time this is registered and a visualChange is created we have essentially lost the "context" of this change and have no way of finding out which elements were modified, meaning we have to perform a rebuild or similar on the entire graph. Likewise the current implementation of NodeLabelBatcher (and other batches) requires a full recreation of the buffers sent to the GLCanavs which further complicates performing changes only for certain elements even when we have a list of those elements.
We may be able to refactor the framework to readily allow for partial changes and which shifts the emphasis for reporting changes away from modification counters and onto the plugins causing the changes (where we have more context). This may lead to performance improvements.

3) Heuristic/Contextual Improvements. This could take many forms but one example may be changing the level of multithreading based on the size of the graph. When we multithread NodeLabelBatcher we are increasing memory usage and CPU utilisations for speed. For smaller graphs we may wish to avoid multithreading to reduce memory usage when doing things like deleting nodes.
Alternatively we may wish two have a "large graph compatability mode" with a faster version of renderTextAsLigatures (with less font compatability) to allow for working on larger graphs with reasonable performance at a cost of some of the nice-to-haves that reduce performance.

I;m sure there are many other ways to get performance improvements, these are just some of the ideas I have had.
