### ISSUE TITLE
Make the active graph tab more obvious

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#997]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The active graph tab in Constellation is very light blue when selected and gray when not active. With many graphs open it is difficult to know which graph is active.

![image](https://user-images.githubusercontent.com/39325530/111941900-3c342300-8b26-11eb-8a02-73a323add3c1.png)

**Comment by Delphinus8821** [comment]
@arcturus2 Having a look at this, this is linked to the NetBeans Look and Feel options. Some of the dark themes make it more obvious than others. The FlatLaf Dark one makes it the most obvious while still being able to see the menu icons the easiest.

**Comment by aldebaran30701** [comment]
Looking at the current release - it seems that the default LAF is dark ? or is that a preference somewhere?

If it's the default, Maybe we look to support Flat LAF Dark as the default dark mode.
![image](https://user-images.githubusercontent.com/58677759/120568852-eba94200-c453-11eb-82c1-e20180ba73f5.png)

Looking below, is Flat LAF Light - for those who don't like dark mode. As seen, it displays the active tab pretty easily.
![image](https://user-images.githubusercontent.com/58677759/120569047-4e9ad900-c454-11eb-9114-ba3637b87d34.png)

This seems to me like a very pedantic issue if it is talking about making the active tab more obvious for a particular style. I'm thinking it's out of scope - Correct me if i am wrong - There could be a different default style which we support instead of flat LAF light.
To note: users don't run from source - and it appears to me that when you launch from source the display for netbeans is different from the current release v2.3.0

**Comment by arcturus2** [comment]
@aldebaran30701 the default isn't Dark LAF though I want it to be. I'd like to focus on colours a bit more for the next release i.e v2.4 if that can be justified and make it the default. I think it can be controlled via the `etc/constellation.conf` file though we'd need to look up how to set the value.

>This seems to me like a very pedantic issue if it is talking about making the active tab more obvious for a particular style.

I disagree regarding the comment its a pedantic issue because if you have a look at the original screenshot in the description it is hard to see which tab is active...though it could be my old age too. However we can limit what we officially support to the Dark LAF and Light LAF you have shown. I'm OK with that.

> To note: users don't run from source - and it appears to me that when you launch from source the display for netbeans is different from the current release v2.3.0

Correct. It might be because you are using Dark LAF for your NetBeans. I think we can control it in the conf file or there might be a programatic access via one of the NetBeans "openide" modules.

**Comment by aldebaran30701** [comment]
>I disagree regarding the comment its a pedantic issue

Pedantic with respect to us fixing it for the specific style - if its the default style it is understandable. No not your old age - upon first look of the screenshot I couldn't tell which one was active 😃 

I agree this needs some solution considering it actually just follows what my NetBeans preferences are. I couldn't find Constellation config that mentioned the preference - It's probably in the actual NetBeans preferences. and that's why I couldn't find it.

**Comment by aldebaran30701** [comment]
As Constellation is looking to support Dark-mode as default in release 2.4 it is probably worthwhile noting that this may not be much of a priority. BUT, given that this ticket shouldn't be hard to fix in the meantime it is worthwhile keeping as it was actually logged as an issue.

**Comment by Delphinus8821** [comment]
From my research into this ticket, we are able to set the look and feel to one of the default swing look and feels through the run.args.extra in project.properties (for the Metal look and feel that is done with either --laf javax.swing.plaf.metal.MetalLookAndFeel or --laf Metal). When you set this in project.properties it disables the drop down list for the look and feel in the options menu, so the user is not able to change it from the one set. 

This also only works with the default look and feels set in swing (e.g. Metal, Nimbus, Motif). I was not able to get this to work with the dark theme version of Metal or Nimbus, and I could not get it to work with the FlatLaf look and feel either.

**Comment by GammaVel** [comment]
also consider #1314 when fixing this one.

**Comment by OrionsGuardian** [comment]
There is now some work in progress to alter the main window tabs so they will be shown in a blue coloured background, making them much easier to distinguish. This is being done programmatically, after the Look and Feel is loaded, to adjust the colours of the tabs. Each Look and Feel needs to be catered for separately.

**Comment by GammaVel** [comment]
Thank you @OrionsGuardian for making this change to improve the display, it looks great with all the different display options (there really are a huge lot to choose from in Constellation!).  The blue on the active graph tab stands out with all the different Look and Feel themes. I tried it out for new and existing graphs. Here is what is looks like for me:

![image](https://user-images.githubusercontent.com/83679004/187331902-d20f8823-0608-4808-9d40-29fae8280b3f.png)

There was one theme (Metal) where the view bar became highlighted in blue but it was still easy to see the graph tab that was active and the view tab that was selected. 

Thanks again
